In [1]:
i = 10

In [2]:
a = 5

In [3]:
a * i

50

In [4]:
a * a

25

In [5]:
i = 7

In [6]:
a * i

35

In [7]:
x = 10

In [8]:
X = 5

In [9]:
print(x)

10


In [10]:
print(X)

5


In [11]:
x*X

50

In [12]:
x = 0

In [13]:
x*x + 3*x + 40

40

In [14]:
x = 5

In [15]:
x*x + 3*x + 40

80

In [16]:
import numpy as np
## SHIFT+ENTER

In [17]:
a = np.array([1.0,2.0,3])

In [18]:
a

array([1., 2., 3.])

In [19]:
type(a)

numpy.ndarray

In [20]:
a.dtype

dtype('float64')

In [21]:
a.ndim

1

In [22]:
a = np.arange(15).reshape(3, 5)

In [23]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
a.ndim

2

In [25]:
a.size

15

In [26]:
a.shape

(3, 5)

In [27]:
a.dtype

dtype('int64')

In [28]:
a.itemsize

8

In [29]:
b = np.array(['xyz','wery'])

In [30]:
b

array(['xyz', 'wery'], dtype='<U4')

In [31]:
b.dtype

dtype('<U4')

In [32]:
b.dtype.name

'str128'

In [33]:
c = np.array([1,2,3], dtype=complex)

In [34]:
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [35]:
c.dtype

dtype('complex128')

In [36]:
c.dtype.name

'complex128'

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.zeros((3,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
d = np.ones((4,4))

In [42]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
d.dtype

dtype('float64')

In [44]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
x = np.arange(0,10,0.2)

In [48]:
x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [49]:
x.dtype

dtype('float64')

In [50]:
x = np.arange(0,10)

In [51]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
x+4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [53]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [54]:
y = x + 5

In [55]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
y

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
z = x+y

In [58]:
z

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [59]:
np.sqrt(y)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [60]:
z = x + np.sqrt(y)

In [61]:
z

array([ 2.23606798,  3.44948974,  4.64575131,  5.82842712,  7.        ,
        8.16227766,  9.31662479, 10.46410162, 11.60555128, 12.74165739])

In [62]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.dot(x,z)

435.7054487727669

In [64]:
x.dot(z)

435.7054487727669

In [65]:
z.dot(x)

435.7054487727669

In [66]:
z

array([ 2.23606798,  3.44948974,  4.64575131,  5.82842712,  7.        ,
        8.16227766,  9.31662479, 10.46410162, 11.60555128, 12.74165739])

In [67]:
x += 1

In [68]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
x -=1

In [70]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x *=2

In [72]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [73]:
x + 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [74]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [75]:
y = np.sqrt(x)

In [76]:
y

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

In [77]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
np.log(x+1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])

In [79]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [80]:
a.sum()

105

In [81]:
a.min()

0

In [82]:
x += 1

In [83]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [84]:
x.min()

1

In [85]:
np.sin(x)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [86]:
np.sin(x)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [87]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [88]:
x.max()

19

In [89]:
x.mean()

10.0

In [90]:
x.std()

5.744562646538029

In [91]:
a = np.arange(10,16)

In [92]:
a

array([10, 11, 12, 13, 14, 15])

In [93]:
a[0]

10

In [94]:
a[1]

11

In [95]:
a[4]

14

In [96]:
a[-1]

15

In [97]:
a[0]

10

In [98]:
a

array([10, 11, 12, 13, 14, 15])

In [99]:
a = np.arange(10)

In [100]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
a = np.sqrt(a)

In [102]:
a

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [103]:
a = np.arange(87)

In [104]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86])

In [105]:
a[-1]

86

In [106]:
a[-2]

85

In [107]:
a[[1,3,4]]

array([1, 3, 4])

In [108]:
a[[0,-1]]

array([ 0, 86])

In [109]:
a[[11,13,-2]]

array([11, 13, 85])

In [110]:
a[[11,13,-1]]

array([11, 13, 86])

In [111]:
a[[11,13,-2,86]]

array([11, 13, 85, 86])

In [112]:
a = np.arange(9).reshape(3,3)

In [113]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [114]:
a[1,2]

5

In [115]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
a[2,2]

8

In [117]:
a[0,0]

0

In [118]:
a[1,1]

4

In [119]:
a[11]

IndexError: index 11 is out of bounds for axis 0 with size 3

In [ ]:
a[1]

In [ ]:
a[0]

In [ ]:
a = np.arange(16)

In [ ]:
a

In [ ]:
a[[6,7,8,9,10]]

In [ ]:
a  = np.arange(99)

In [ ]:
a

In [ ]:
a[22:88]

In [ ]:
a += 1

In [ ]:
a

In [ ]:
a[22:88]

In [ ]:
a[22:88:92]

In [ ]:
a[22:88:2]

In [ ]:
a[22:88:1]

In [ ]:
a[22:88:-1]

In [ ]:
a[22:88:1]

In [ ]:
a[22:88:2]

In [ ]:
a[22:88:3]

In [ ]:
a[22:88:10]

In [ ]:
a = np.arange(100,200)

In [ ]:
a

In [ ]:
a[22:88:10]

In [ ]:
a[22:88:-1]

In [ ]:
a[88:22:-1]

In [ ]:
a[::1]

In [ ]:
a[::2]

In [ ]:
a[:5:]

In [ ]:
a = np.arange(10,19).reshape(3,3)

In [ ]:
a

In [ ]:
a[0]

In [ ]:
a[1]

In [ ]:
a[2]

In [ ]:
a[0,:]

In [ ]:
a[:,0]

In [ ]:
a[:,1]

In [ ]:
a

In [ ]:
a[0:1,0:1]

In [ ]:
a[0:1,0:2]

In [ ]:
a[0:2,0:2]

In [ ]:
a[[0,2],0:2]

In [ ]:
a

In [ ]:
for i in a :
    print(i)
    print("---")

In [ ]:
a.flat

In [ ]:
for item in a.flat:
    print(item)
    print("-----")

In [120]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [121]:
np.apply_along_axis(np.mean,axis=0,arr=a)

array([3., 4., 5.])

In [122]:
np.apply_along_axis(np.mean,axis=1,arr=a)

array([1., 4., 7.])

In [123]:
def halfOfValue(x):
    return x/2


In [124]:
np.apply_along_axis(halfOfValue,axis=0,arr=a)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [125]:
np.apply_along_axis(halfOfValue,axis=1,arr=a)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [126]:
def doubleOfValue(x):
    return 2*x


In [127]:
np.apply_along_axis(doubleOfValue,axis=1,arr=a)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [128]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
def substractOne(x):
    return x-1

In [130]:
np.apply_along_axis(substractOne,axis=0,arr=a)

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [131]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [132]:
a[0]

array([0, 1, 2])

In [133]:
a = np.random.random((4,4))

In [134]:
a

array([[0.92901327, 0.71094459, 0.01735287, 0.37693376],
       [0.47271295, 0.91222211, 0.84010164, 0.66262554],
       [0.36204628, 0.81077851, 0.75791578, 0.99341958],
       [0.02372879, 0.24247506, 0.59590525, 0.20643598]])

In [135]:
a < 0.5

array([[False, False,  True,  True],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True,  True, False,  True]])

In [136]:
b = a < 0.5

In [137]:
b

array([[False, False,  True,  True],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True,  True, False,  True]])

In [138]:
c = a > 0.6

In [139]:
c

array([[ True,  True, False, False],
       [False,  True,  True,  True],
       [False,  True,  True,  True],
       [False, False, False, False]])

In [140]:
c.dtype

dtype('bool')

In [141]:
b = a[a < 0.5]

In [142]:
b

array([0.01735287, 0.37693376, 0.47271295, 0.36204628, 0.02372879,
       0.24247506, 0.20643598])

In [143]:
a

array([[0.92901327, 0.71094459, 0.01735287, 0.37693376],
       [0.47271295, 0.91222211, 0.84010164, 0.66262554],
       [0.36204628, 0.81077851, 0.75791578, 0.99341958],
       [0.02372879, 0.24247506, 0.59590525, 0.20643598]])

In [144]:
b = a[a > 0.5]

In [145]:
b

array([0.92901327, 0.71094459, 0.91222211, 0.84010164, 0.66262554,
       0.81077851, 0.75791578, 0.99341958, 0.59590525])

In [158]:
a = np.random.random((4,4))

In [159]:
b

array([0.78012206, 0.93674955, 0.78827182, 0.83340097, 0.53666861,
       0.50595173])

In [160]:
a

array([[0.79078663, 0.49505892, 0.20818806, 0.06264601],
       [0.63364027, 0.81413481, 0.63902849, 0.14494608],
       [0.42091761, 0.15305952, 0.7812497 , 0.74273315],
       [0.75385417, 0.2668867 , 0.72342004, 0.31139823]])

In [154]:
b = a[a > 0.5]

In [167]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
        0.96400068],
       [0.23659126, 0.04740352, 0.06892495, 0.7434043 , 0.11450833,
        0.07771495]])

In [156]:
b

array([0.78012206, 0.93674955, 0.78827182, 0.83340097, 0.53666861,
       0.50595173])

In [161]:
a = np.random.random(12)

In [162]:
a

array([0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
       0.96400068, 0.23659126, 0.04740352, 0.06892495, 0.7434043 ,
       0.11450833, 0.07771495])

In [165]:
a = a.reshape(2,6)

In [166]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
        0.96400068],
       [0.23659126, 0.04740352, 0.06892495, 0.7434043 , 0.11450833,
        0.07771495]])

In [169]:
a.shape = (3,4)

In [170]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598],
       [0.94090523, 0.96400068, 0.23659126, 0.04740352],
       [0.06892495, 0.7434043 , 0.11450833, 0.07771495]])

In [171]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598],
       [0.94090523, 0.96400068, 0.23659126, 0.04740352],
       [0.06892495, 0.7434043 , 0.11450833, 0.07771495]])

In [172]:
a.ravel()

array([0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
       0.96400068, 0.23659126, 0.04740352, 0.06892495, 0.7434043 ,
       0.11450833, 0.07771495])

In [173]:
b = a

In [174]:
b

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598],
       [0.94090523, 0.96400068, 0.23659126, 0.04740352],
       [0.06892495, 0.7434043 , 0.11450833, 0.07771495]])

In [175]:
b.shape = (12)

In [176]:
b

array([0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
       0.96400068, 0.23659126, 0.04740352, 0.06892495, 0.7434043 ,
       0.11450833, 0.07771495])

In [177]:
a

array([0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
       0.96400068, 0.23659126, 0.04740352, 0.06892495, 0.7434043 ,
       0.11450833, 0.07771495])

In [178]:
a.transpose()

array([0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
       0.96400068, 0.23659126, 0.04740352, 0.06892495, 0.7434043 ,
       0.11450833, 0.07771495])

In [179]:
a.shape = (2,6)

In [180]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
        0.96400068],
       [0.23659126, 0.04740352, 0.06892495, 0.7434043 , 0.11450833,
        0.07771495]])

In [183]:
b = a.transpose()

In [184]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
        0.96400068],
       [0.23659126, 0.04740352, 0.06892495, 0.7434043 , 0.11450833,
        0.07771495]])

In [185]:
b

array([[0.09174265, 0.23659126],
       [0.89005504, 0.04740352],
       [0.74979389, 0.06892495],
       [0.28681598, 0.7434043 ],
       [0.94090523, 0.11450833],
       [0.96400068, 0.07771495]])

In [186]:
a = np.ones((3,3))

In [187]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [188]:
b = np.zeros((3,3))

In [189]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [190]:
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [191]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [192]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [193]:
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [194]:
a = np.arange(16).reshape((4,4))

In [195]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [196]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [197]:
[b,c] = np.hsplit(a,2)

In [198]:
b

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [199]:
c

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [200]:
[b,c] = np.vsplit(a,2)

In [201]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [202]:
c

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [203]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [204]:
b = a

In [205]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [206]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [211]:
b = np.arange(16)

In [208]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [209]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [210]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [212]:
c = a

In [213]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [214]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [215]:
c.shape = (2,8)

In [216]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [217]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [218]:
a.shape=(4,4)

In [219]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [220]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [221]:
c = a.copy()

In [222]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [223]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [224]:
c.shape = (2,8)

In [225]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [226]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [227]:
a.shape=(8,2)

In [228]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [229]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [230]:
a 

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [231]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [232]:
a.shape = (4,4)

In [233]:
c.shape = (4,4)

In [234]:
a * c

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [235]:
a = np.arange(16).reshape(4,4)

In [236]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [237]:
b = np.arange(4)

In [239]:
b

array([0, 1, 2, 3])

In [240]:
a * b

array([[ 0,  1,  4,  9],
       [ 0,  5, 12, 21],
       [ 0,  9, 20, 33],
       [ 0, 13, 28, 45]])

In [241]:
a + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [242]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [243]:
b

array([0, 1, 2, 3])

In [244]:
a = np.arange(6).reshape(3,1,2)

In [245]:
a

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [246]:
b = np.arange(6).reshape(3,2,1)

In [247]:
b

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [248]:
a + b

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

In [275]:
a = np.array([(1,'First', 0.2,1+2j),(2,'Second', 0.4,1-2j),(3,'Third', 0.3,3+2j)],
             dtype=[('id','i2'),('position','a6'),('value','f4'),('complex','c8')])

In [276]:
a

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (3, b'Third', 0.3, 3.+2.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [265]:
a[0]

(1, b'First', 0.2, 1.+2.j)

In [266]:
a[1]

(2, b'Second', 0.4, 1.-2.j)

In [267]:
a[2]

(3, b'Third', 0.3, 3.+2.j)

In [268]:
a[0]

(1, b'First', 0.2, 1.+2.j)

In [270]:
a['id']

array([1, 2, 3], dtype=int16)

In [272]:
a['position']

array([b'First', b'Second', b'Third'], dtype='|S6')

In [273]:
a['value']

array([0.2, 0.4, 0.3], dtype=float32)

In [274]:
a['complex']

array([1.+2.j, 1.-2.j, 3.+2.j], dtype=complex64)

In [279]:
a.dtype.names=('idx','order','valuex','cplx')

In [280]:
a

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (3, b'Third', 0.3, 3.+2.j)],
      dtype=[('idx', '<i2'), ('order', 'S6'), ('valuex', '<f4'), ('cplx', '<c8')])

In [281]:
a

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (3, b'Third', 0.3, 3.+2.j)],
      dtype=[('idx', '<i2'), ('order', 'S6'), ('valuex', '<f4'), ('cplx', '<c8')])

In [283]:
np.save('saved_data',a)

In [284]:
data = np.load('saved_data.npy')

In [285]:
data

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (3, b'Third', 0.3, 3.+2.j)],
      dtype=[('idx', '<i2'), ('order', 'S6'), ('valuex', '<f4'), ('cplx', '<c8')])

In [290]:
data = np.genfromtxt('02_data.csv',delimiter=',',names=True)

In [291]:
data

array([(1., nan, 34.), (2., nan, 56.), (3., nan, 96.)],
      dtype=[('id', '<f8'), ('position', '<f8'), ('value', '<f8')])

In [293]:
data['id']

array([1., 2., 3.])

In [294]:
data[0]

(1., nan, 34.)

In [295]:
data[1]

(2., nan, 56.)

In [296]:
data[2]

(3., nan, 96.)

In [297]:
data = np.genfromtxt('01_data.csv',delimiter=',',names=True)

ValueError: Some errors were detected !
    Line #2 (got 13 columns instead of 12)
    Line #3 (got 13 columns instead of 12)
    Line #4 (got 13 columns instead of 12)
    Line #5 (got 13 columns instead of 12)
    Line #6 (got 13 columns instead of 12)
    Line #7 (got 13 columns instead of 12)
    Line #8 (got 13 columns instead of 12)
    Line #9 (got 13 columns instead of 12)
    Line #10 (got 13 columns instead of 12)
    Line #11 (got 13 columns instead of 12)
    Line #12 (got 13 columns instead of 12)
    Line #13 (got 13 columns instead of 12)
    Line #14 (got 13 columns instead of 12)
    Line #15 (got 13 columns instead of 12)
    Line #16 (got 13 columns instead of 12)
    Line #17 (got 13 columns instead of 12)
    Line #18 (got 13 columns instead of 12)
    Line #19 (got 13 columns instead of 12)
    Line #20 (got 13 columns instead of 12)
    Line #21 (got 13 columns instead of 12)
    Line #22 (got 13 columns instead of 12)
    Line #23 (got 13 columns instead of 12)
    Line #24 (got 13 columns instead of 12)
    Line #25 (got 13 columns instead of 12)
    Line #26 (got 13 columns instead of 12)
    Line #27 (got 13 columns instead of 12)
    Line #28 (got 13 columns instead of 12)
    Line #29 (got 13 columns instead of 12)
    Line #30 (got 13 columns instead of 12)
    Line #31 (got 13 columns instead of 12)
    Line #32 (got 13 columns instead of 12)
    Line #33 (got 13 columns instead of 12)
    Line #34 (got 13 columns instead of 12)
    Line #35 (got 13 columns instead of 12)
    Line #36 (got 13 columns instead of 12)
    Line #37 (got 13 columns instead of 12)
    Line #38 (got 13 columns instead of 12)
    Line #39 (got 13 columns instead of 12)
    Line #40 (got 13 columns instead of 12)
    Line #41 (got 13 columns instead of 12)
    Line #42 (got 13 columns instead of 12)
    Line #43 (got 13 columns instead of 12)
    Line #44 (got 13 columns instead of 12)
    Line #45 (got 13 columns instead of 12)
    Line #46 (got 13 columns instead of 12)
    Line #47 (got 13 columns instead of 12)
    Line #48 (got 13 columns instead of 12)
    Line #49 (got 13 columns instead of 12)
    Line #50 (got 13 columns instead of 12)
    Line #51 (got 13 columns instead of 12)
    Line #52 (got 13 columns instead of 12)
    Line #53 (got 13 columns instead of 12)
    Line #54 (got 13 columns instead of 12)
    Line #55 (got 13 columns instead of 12)
    Line #56 (got 13 columns instead of 12)
    Line #57 (got 13 columns instead of 12)
    Line #58 (got 13 columns instead of 12)
    Line #59 (got 13 columns instead of 12)
    Line #60 (got 13 columns instead of 12)
    Line #61 (got 13 columns instead of 12)
    Line #62 (got 13 columns instead of 12)
    Line #63 (got 13 columns instead of 12)
    Line #64 (got 13 columns instead of 12)
    Line #65 (got 13 columns instead of 12)
    Line #66 (got 13 columns instead of 12)
    Line #67 (got 13 columns instead of 12)
    Line #68 (got 13 columns instead of 12)
    Line #69 (got 13 columns instead of 12)
    Line #70 (got 13 columns instead of 12)
    Line #71 (got 13 columns instead of 12)
    Line #72 (got 13 columns instead of 12)
    Line #73 (got 13 columns instead of 12)
    Line #74 (got 13 columns instead of 12)
    Line #75 (got 13 columns instead of 12)
    Line #76 (got 13 columns instead of 12)
    Line #77 (got 13 columns instead of 12)
    Line #78 (got 13 columns instead of 12)
    Line #79 (got 13 columns instead of 12)
    Line #80 (got 13 columns instead of 12)
    Line #81 (got 13 columns instead of 12)
    Line #82 (got 13 columns instead of 12)
    Line #83 (got 13 columns instead of 12)
    Line #84 (got 13 columns instead of 12)
    Line #85 (got 13 columns instead of 12)
    Line #86 (got 13 columns instead of 12)
    Line #87 (got 13 columns instead of 12)
    Line #88 (got 13 columns instead of 12)
    Line #89 (got 13 columns instead of 12)
    Line #90 (got 13 columns instead of 12)
    Line #91 (got 13 columns instead of 12)
    Line #92 (got 13 columns instead of 12)
    Line #93 (got 13 columns instead of 12)
    Line #94 (got 13 columns instead of 12)
    Line #95 (got 13 columns instead of 12)
    Line #96 (got 13 columns instead of 12)
    Line #97 (got 13 columns instead of 12)
    Line #98 (got 13 columns instead of 12)
    Line #99 (got 13 columns instead of 12)
    Line #100 (got 13 columns instead of 12)
    Line #101 (got 13 columns instead of 12)
    Line #102 (got 13 columns instead of 12)
    Line #103 (got 13 columns instead of 12)
    Line #104 (got 13 columns instead of 12)
    Line #105 (got 13 columns instead of 12)
    Line #106 (got 13 columns instead of 12)
    Line #107 (got 13 columns instead of 12)
    Line #108 (got 13 columns instead of 12)
    Line #109 (got 13 columns instead of 12)
    Line #110 (got 13 columns instead of 12)
    Line #111 (got 13 columns instead of 12)
    Line #112 (got 13 columns instead of 12)
    Line #113 (got 13 columns instead of 12)
    Line #114 (got 13 columns instead of 12)
    Line #115 (got 13 columns instead of 12)
    Line #116 (got 13 columns instead of 12)
    Line #117 (got 13 columns instead of 12)
    Line #118 (got 13 columns instead of 12)
    Line #119 (got 13 columns instead of 12)
    Line #120 (got 13 columns instead of 12)
    Line #121 (got 13 columns instead of 12)
    Line #122 (got 13 columns instead of 12)
    Line #123 (got 13 columns instead of 12)
    Line #124 (got 13 columns instead of 12)
    Line #125 (got 13 columns instead of 12)
    Line #126 (got 13 columns instead of 12)
    Line #127 (got 13 columns instead of 12)
    Line #128 (got 13 columns instead of 12)
    Line #129 (got 13 columns instead of 12)
    Line #130 (got 13 columns instead of 12)
    Line #131 (got 13 columns instead of 12)
    Line #132 (got 13 columns instead of 12)
    Line #133 (got 13 columns instead of 12)
    Line #134 (got 13 columns instead of 12)
    Line #135 (got 13 columns instead of 12)
    Line #136 (got 13 columns instead of 12)
    Line #137 (got 13 columns instead of 12)
    Line #138 (got 13 columns instead of 12)
    Line #139 (got 13 columns instead of 12)
    Line #140 (got 13 columns instead of 12)
    Line #141 (got 13 columns instead of 12)
    Line #142 (got 13 columns instead of 12)
    Line #143 (got 13 columns instead of 12)
    Line #144 (got 13 columns instead of 12)
    Line #145 (got 13 columns instead of 12)
    Line #146 (got 13 columns instead of 12)
    Line #147 (got 13 columns instead of 12)
    Line #148 (got 13 columns instead of 12)
    Line #149 (got 13 columns instead of 12)
    Line #150 (got 13 columns instead of 12)
    Line #151 (got 13 columns instead of 12)
    Line #152 (got 13 columns instead of 12)
    Line #153 (got 13 columns instead of 12)
    Line #154 (got 13 columns instead of 12)
    Line #155 (got 13 columns instead of 12)
    Line #156 (got 13 columns instead of 12)
    Line #157 (got 13 columns instead of 12)
    Line #158 (got 13 columns instead of 12)
    Line #159 (got 13 columns instead of 12)
    Line #160 (got 13 columns instead of 12)
    Line #161 (got 13 columns instead of 12)
    Line #162 (got 13 columns instead of 12)
    Line #163 (got 13 columns instead of 12)
    Line #164 (got 13 columns instead of 12)
    Line #165 (got 13 columns instead of 12)
    Line #166 (got 13 columns instead of 12)
    Line #167 (got 13 columns instead of 12)
    Line #168 (got 13 columns instead of 12)
    Line #169 (got 13 columns instead of 12)
    Line #170 (got 13 columns instead of 12)
    Line #171 (got 13 columns instead of 12)
    Line #172 (got 13 columns instead of 12)
    Line #173 (got 13 columns instead of 12)
    Line #174 (got 13 columns instead of 12)
    Line #175 (got 13 columns instead of 12)
    Line #176 (got 13 columns instead of 12)
    Line #177 (got 13 columns instead of 12)
    Line #178 (got 13 columns instead of 12)
    Line #179 (got 13 columns instead of 12)
    Line #180 (got 13 columns instead of 12)
    Line #181 (got 13 columns instead of 12)
    Line #182 (got 13 columns instead of 12)
    Line #183 (got 13 columns instead of 12)
    Line #184 (got 13 columns instead of 12)
    Line #185 (got 13 columns instead of 12)
    Line #186 (got 13 columns instead of 12)
    Line #187 (got 13 columns instead of 12)
    Line #188 (got 13 columns instead of 12)
    Line #189 (got 13 columns instead of 12)
    Line #190 (got 13 columns instead of 12)
    Line #191 (got 13 columns instead of 12)
    Line #192 (got 13 columns instead of 12)
    Line #193 (got 13 columns instead of 12)
    Line #194 (got 13 columns instead of 12)
    Line #195 (got 13 columns instead of 12)
    Line #196 (got 13 columns instead of 12)
    Line #197 (got 13 columns instead of 12)
    Line #198 (got 13 columns instead of 12)
    Line #199 (got 13 columns instead of 12)
    Line #200 (got 13 columns instead of 12)
    Line #201 (got 13 columns instead of 12)
    Line #202 (got 13 columns instead of 12)
    Line #203 (got 13 columns instead of 12)
    Line #204 (got 13 columns instead of 12)
    Line #205 (got 13 columns instead of 12)
    Line #206 (got 13 columns instead of 12)
    Line #207 (got 13 columns instead of 12)
    Line #208 (got 13 columns instead of 12)
    Line #209 (got 13 columns instead of 12)
    Line #210 (got 13 columns instead of 12)
    Line #211 (got 13 columns instead of 12)
    Line #212 (got 13 columns instead of 12)
    Line #213 (got 13 columns instead of 12)
    Line #214 (got 13 columns instead of 12)
    Line #215 (got 13 columns instead of 12)
    Line #216 (got 13 columns instead of 12)
    Line #217 (got 13 columns instead of 12)
    Line #218 (got 13 columns instead of 12)
    Line #219 (got 13 columns instead of 12)
    Line #220 (got 13 columns instead of 12)
    Line #221 (got 13 columns instead of 12)
    Line #222 (got 13 columns instead of 12)
    Line #223 (got 13 columns instead of 12)
    Line #224 (got 13 columns instead of 12)
    Line #225 (got 13 columns instead of 12)
    Line #226 (got 13 columns instead of 12)
    Line #227 (got 13 columns instead of 12)
    Line #228 (got 13 columns instead of 12)
    Line #229 (got 13 columns instead of 12)
    Line #230 (got 13 columns instead of 12)
    Line #231 (got 13 columns instead of 12)
    Line #232 (got 13 columns instead of 12)
    Line #233 (got 13 columns instead of 12)
    Line #234 (got 13 columns instead of 12)
    Line #235 (got 13 columns instead of 12)
    Line #236 (got 13 columns instead of 12)
    Line #237 (got 13 columns instead of 12)
    Line #238 (got 13 columns instead of 12)
    Line #239 (got 13 columns instead of 12)
    Line #240 (got 13 columns instead of 12)
    Line #241 (got 13 columns instead of 12)
    Line #242 (got 13 columns instead of 12)
    Line #243 (got 13 columns instead of 12)
    Line #244 (got 13 columns instead of 12)
    Line #245 (got 13 columns instead of 12)
    Line #246 (got 13 columns instead of 12)
    Line #247 (got 13 columns instead of 12)
    Line #248 (got 13 columns instead of 12)
    Line #249 (got 13 columns instead of 12)
    Line #250 (got 13 columns instead of 12)
    Line #251 (got 13 columns instead of 12)
    Line #252 (got 13 columns instead of 12)
    Line #253 (got 13 columns instead of 12)
    Line #254 (got 13 columns instead of 12)
    Line #255 (got 13 columns instead of 12)
    Line #256 (got 13 columns instead of 12)
    Line #257 (got 13 columns instead of 12)
    Line #258 (got 13 columns instead of 12)
    Line #259 (got 13 columns instead of 12)
    Line #260 (got 13 columns instead of 12)
    Line #261 (got 13 columns instead of 12)
    Line #262 (got 13 columns instead of 12)
    Line #263 (got 13 columns instead of 12)
    Line #264 (got 13 columns instead of 12)
    Line #265 (got 13 columns instead of 12)
    Line #266 (got 13 columns instead of 12)
    Line #267 (got 13 columns instead of 12)
    Line #268 (got 13 columns instead of 12)
    Line #269 (got 13 columns instead of 12)
    Line #270 (got 13 columns instead of 12)
    Line #271 (got 13 columns instead of 12)
    Line #272 (got 13 columns instead of 12)
    Line #273 (got 13 columns instead of 12)
    Line #274 (got 13 columns instead of 12)
    Line #275 (got 13 columns instead of 12)
    Line #276 (got 13 columns instead of 12)
    Line #277 (got 13 columns instead of 12)
    Line #278 (got 13 columns instead of 12)
    Line #279 (got 13 columns instead of 12)
    Line #280 (got 13 columns instead of 12)
    Line #281 (got 13 columns instead of 12)
    Line #282 (got 13 columns instead of 12)
    Line #283 (got 13 columns instead of 12)
    Line #284 (got 13 columns instead of 12)
    Line #285 (got 13 columns instead of 12)
    Line #286 (got 13 columns instead of 12)
    Line #287 (got 13 columns instead of 12)
    Line #288 (got 13 columns instead of 12)
    Line #289 (got 13 columns instead of 12)
    Line #290 (got 13 columns instead of 12)
    Line #291 (got 13 columns instead of 12)
    Line #292 (got 13 columns instead of 12)
    Line #293 (got 13 columns instead of 12)
    Line #294 (got 13 columns instead of 12)
    Line #295 (got 13 columns instead of 12)
    Line #296 (got 13 columns instead of 12)
    Line #297 (got 13 columns instead of 12)
    Line #298 (got 13 columns instead of 12)
    Line #299 (got 13 columns instead of 12)
    Line #300 (got 13 columns instead of 12)
    Line #301 (got 13 columns instead of 12)
    Line #302 (got 13 columns instead of 12)
    Line #303 (got 13 columns instead of 12)
    Line #304 (got 13 columns instead of 12)
    Line #305 (got 13 columns instead of 12)
    Line #306 (got 13 columns instead of 12)
    Line #307 (got 13 columns instead of 12)
    Line #308 (got 13 columns instead of 12)
    Line #309 (got 13 columns instead of 12)
    Line #310 (got 13 columns instead of 12)
    Line #311 (got 13 columns instead of 12)
    Line #312 (got 13 columns instead of 12)
    Line #313 (got 13 columns instead of 12)
    Line #314 (got 13 columns instead of 12)
    Line #315 (got 13 columns instead of 12)
    Line #316 (got 13 columns instead of 12)
    Line #317 (got 13 columns instead of 12)
    Line #318 (got 13 columns instead of 12)
    Line #319 (got 13 columns instead of 12)
    Line #320 (got 13 columns instead of 12)
    Line #321 (got 13 columns instead of 12)
    Line #322 (got 13 columns instead of 12)
    Line #323 (got 13 columns instead of 12)
    Line #324 (got 13 columns instead of 12)
    Line #325 (got 13 columns instead of 12)
    Line #326 (got 13 columns instead of 12)
    Line #327 (got 13 columns instead of 12)
    Line #328 (got 13 columns instead of 12)
    Line #329 (got 13 columns instead of 12)
    Line #330 (got 13 columns instead of 12)
    Line #331 (got 13 columns instead of 12)
    Line #332 (got 13 columns instead of 12)
    Line #333 (got 13 columns instead of 12)
    Line #334 (got 13 columns instead of 12)
    Line #335 (got 13 columns instead of 12)
    Line #336 (got 13 columns instead of 12)
    Line #337 (got 13 columns instead of 12)
    Line #338 (got 13 columns instead of 12)
    Line #339 (got 13 columns instead of 12)
    Line #340 (got 13 columns instead of 12)
    Line #341 (got 13 columns instead of 12)
    Line #342 (got 13 columns instead of 12)
    Line #343 (got 13 columns instead of 12)
    Line #344 (got 13 columns instead of 12)
    Line #345 (got 13 columns instead of 12)
    Line #346 (got 13 columns instead of 12)
    Line #347 (got 13 columns instead of 12)
    Line #348 (got 13 columns instead of 12)
    Line #349 (got 13 columns instead of 12)
    Line #350 (got 13 columns instead of 12)
    Line #351 (got 13 columns instead of 12)
    Line #352 (got 13 columns instead of 12)
    Line #353 (got 13 columns instead of 12)
    Line #354 (got 13 columns instead of 12)
    Line #355 (got 13 columns instead of 12)
    Line #356 (got 13 columns instead of 12)
    Line #357 (got 13 columns instead of 12)
    Line #358 (got 13 columns instead of 12)
    Line #359 (got 13 columns instead of 12)
    Line #360 (got 13 columns instead of 12)
    Line #361 (got 13 columns instead of 12)
    Line #362 (got 13 columns instead of 12)
    Line #363 (got 13 columns instead of 12)
    Line #364 (got 13 columns instead of 12)
    Line #365 (got 13 columns instead of 12)
    Line #366 (got 13 columns instead of 12)
    Line #367 (got 13 columns instead of 12)
    Line #368 (got 13 columns instead of 12)
    Line #369 (got 13 columns instead of 12)
    Line #370 (got 13 columns instead of 12)
    Line #371 (got 13 columns instead of 12)
    Line #372 (got 13 columns instead of 12)
    Line #373 (got 13 columns instead of 12)
    Line #374 (got 13 columns instead of 12)
    Line #375 (got 13 columns instead of 12)
    Line #376 (got 13 columns instead of 12)
    Line #377 (got 13 columns instead of 12)
    Line #378 (got 13 columns instead of 12)
    Line #379 (got 13 columns instead of 12)
    Line #380 (got 13 columns instead of 12)
    Line #381 (got 13 columns instead of 12)
    Line #382 (got 13 columns instead of 12)
    Line #383 (got 13 columns instead of 12)
    Line #384 (got 13 columns instead of 12)
    Line #385 (got 13 columns instead of 12)
    Line #386 (got 13 columns instead of 12)
    Line #387 (got 13 columns instead of 12)
    Line #388 (got 13 columns instead of 12)
    Line #389 (got 13 columns instead of 12)
    Line #390 (got 13 columns instead of 12)
    Line #391 (got 13 columns instead of 12)
    Line #392 (got 13 columns instead of 12)
    Line #393 (got 13 columns instead of 12)
    Line #394 (got 13 columns instead of 12)
    Line #395 (got 13 columns instead of 12)
    Line #396 (got 13 columns instead of 12)
    Line #397 (got 13 columns instead of 12)
    Line #398 (got 13 columns instead of 12)
    Line #399 (got 13 columns instead of 12)
    Line #400 (got 13 columns instead of 12)
    Line #401 (got 13 columns instead of 12)
    Line #402 (got 13 columns instead of 12)
    Line #403 (got 13 columns instead of 12)
    Line #404 (got 13 columns instead of 12)
    Line #405 (got 13 columns instead of 12)
    Line #406 (got 13 columns instead of 12)
    Line #407 (got 13 columns instead of 12)
    Line #408 (got 13 columns instead of 12)
    Line #409 (got 13 columns instead of 12)
    Line #410 (got 13 columns instead of 12)
    Line #411 (got 13 columns instead of 12)
    Line #412 (got 13 columns instead of 12)
    Line #413 (got 13 columns instead of 12)
    Line #414 (got 13 columns instead of 12)
    Line #415 (got 13 columns instead of 12)
    Line #416 (got 13 columns instead of 12)
    Line #417 (got 13 columns instead of 12)
    Line #418 (got 13 columns instead of 12)
    Line #419 (got 13 columns instead of 12)
    Line #420 (got 13 columns instead of 12)
    Line #421 (got 13 columns instead of 12)
    Line #422 (got 13 columns instead of 12)
    Line #423 (got 13 columns instead of 12)
    Line #424 (got 13 columns instead of 12)
    Line #425 (got 13 columns instead of 12)
    Line #426 (got 13 columns instead of 12)
    Line #427 (got 13 columns instead of 12)
    Line #428 (got 13 columns instead of 12)
    Line #429 (got 13 columns instead of 12)
    Line #430 (got 13 columns instead of 12)
    Line #431 (got 13 columns instead of 12)
    Line #432 (got 13 columns instead of 12)
    Line #433 (got 13 columns instead of 12)
    Line #434 (got 13 columns instead of 12)
    Line #435 (got 13 columns instead of 12)
    Line #436 (got 13 columns instead of 12)
    Line #437 (got 13 columns instead of 12)
    Line #438 (got 13 columns instead of 12)
    Line #439 (got 13 columns instead of 12)
    Line #440 (got 13 columns instead of 12)
    Line #441 (got 13 columns instead of 12)
    Line #442 (got 13 columns instead of 12)
    Line #443 (got 13 columns instead of 12)
    Line #444 (got 13 columns instead of 12)
    Line #445 (got 13 columns instead of 12)
    Line #446 (got 13 columns instead of 12)
    Line #447 (got 13 columns instead of 12)
    Line #448 (got 13 columns instead of 12)
    Line #449 (got 13 columns instead of 12)
    Line #450 (got 13 columns instead of 12)
    Line #451 (got 13 columns instead of 12)
    Line #452 (got 13 columns instead of 12)
    Line #453 (got 13 columns instead of 12)
    Line #454 (got 13 columns instead of 12)
    Line #455 (got 13 columns instead of 12)
    Line #456 (got 13 columns instead of 12)
    Line #457 (got 13 columns instead of 12)
    Line #458 (got 13 columns instead of 12)
    Line #459 (got 13 columns instead of 12)
    Line #460 (got 13 columns instead of 12)
    Line #461 (got 13 columns instead of 12)
    Line #462 (got 13 columns instead of 12)
    Line #463 (got 13 columns instead of 12)
    Line #464 (got 13 columns instead of 12)
    Line #465 (got 13 columns instead of 12)
    Line #466 (got 13 columns instead of 12)
    Line #467 (got 13 columns instead of 12)
    Line #468 (got 13 columns instead of 12)
    Line #469 (got 13 columns instead of 12)
    Line #470 (got 13 columns instead of 12)
    Line #471 (got 13 columns instead of 12)
    Line #472 (got 13 columns instead of 12)
    Line #473 (got 13 columns instead of 12)
    Line #474 (got 13 columns instead of 12)
    Line #475 (got 13 columns instead of 12)
    Line #476 (got 13 columns instead of 12)
    Line #477 (got 13 columns instead of 12)
    Line #478 (got 13 columns instead of 12)
    Line #479 (got 13 columns instead of 12)
    Line #480 (got 13 columns instead of 12)
    Line #481 (got 13 columns instead of 12)
    Line #482 (got 13 columns instead of 12)
    Line #483 (got 13 columns instead of 12)
    Line #484 (got 13 columns instead of 12)
    Line #485 (got 13 columns instead of 12)
    Line #486 (got 13 columns instead of 12)
    Line #487 (got 13 columns instead of 12)
    Line #488 (got 13 columns instead of 12)
    Line #489 (got 13 columns instead of 12)
    Line #490 (got 13 columns instead of 12)
    Line #491 (got 13 columns instead of 12)
    Line #492 (got 13 columns instead of 12)
    Line #493 (got 13 columns instead of 12)
    Line #494 (got 13 columns instead of 12)
    Line #495 (got 13 columns instead of 12)
    Line #496 (got 13 columns instead of 12)
    Line #497 (got 13 columns instead of 12)
    Line #498 (got 13 columns instead of 12)
    Line #499 (got 13 columns instead of 12)
    Line #500 (got 13 columns instead of 12)
    Line #501 (got 13 columns instead of 12)
    Line #502 (got 13 columns instead of 12)
    Line #503 (got 13 columns instead of 12)
    Line #504 (got 13 columns instead of 12)
    Line #505 (got 13 columns instead of 12)
    Line #506 (got 13 columns instead of 12)
    Line #507 (got 13 columns instead of 12)
    Line #508 (got 13 columns instead of 12)
    Line #509 (got 13 columns instead of 12)
    Line #510 (got 13 columns instead of 12)
    Line #511 (got 13 columns instead of 12)
    Line #512 (got 13 columns instead of 12)
    Line #513 (got 13 columns instead of 12)
    Line #514 (got 13 columns instead of 12)
    Line #515 (got 13 columns instead of 12)
    Line #516 (got 13 columns instead of 12)
    Line #517 (got 13 columns instead of 12)
    Line #518 (got 13 columns instead of 12)
    Line #519 (got 13 columns instead of 12)
    Line #520 (got 13 columns instead of 12)
    Line #521 (got 13 columns instead of 12)
    Line #522 (got 13 columns instead of 12)
    Line #523 (got 13 columns instead of 12)
    Line #524 (got 13 columns instead of 12)
    Line #525 (got 13 columns instead of 12)
    Line #526 (got 13 columns instead of 12)
    Line #527 (got 13 columns instead of 12)
    Line #528 (got 13 columns instead of 12)
    Line #529 (got 13 columns instead of 12)
    Line #530 (got 13 columns instead of 12)
    Line #531 (got 13 columns instead of 12)
    Line #532 (got 13 columns instead of 12)
    Line #533 (got 13 columns instead of 12)
    Line #534 (got 13 columns instead of 12)
    Line #535 (got 13 columns instead of 12)
    Line #536 (got 13 columns instead of 12)
    Line #537 (got 13 columns instead of 12)
    Line #538 (got 13 columns instead of 12)
    Line #539 (got 13 columns instead of 12)
    Line #540 (got 13 columns instead of 12)
    Line #541 (got 13 columns instead of 12)
    Line #542 (got 13 columns instead of 12)
    Line #543 (got 13 columns instead of 12)
    Line #544 (got 13 columns instead of 12)
    Line #545 (got 13 columns instead of 12)
    Line #546 (got 13 columns instead of 12)
    Line #547 (got 13 columns instead of 12)
    Line #548 (got 13 columns instead of 12)
    Line #549 (got 13 columns instead of 12)
    Line #550 (got 13 columns instead of 12)
    Line #551 (got 13 columns instead of 12)
    Line #552 (got 13 columns instead of 12)
    Line #553 (got 13 columns instead of 12)
    Line #554 (got 13 columns instead of 12)
    Line #555 (got 13 columns instead of 12)
    Line #556 (got 13 columns instead of 12)
    Line #557 (got 13 columns instead of 12)
    Line #558 (got 13 columns instead of 12)
    Line #559 (got 13 columns instead of 12)
    Line #560 (got 13 columns instead of 12)
    Line #561 (got 13 columns instead of 12)
    Line #562 (got 13 columns instead of 12)
    Line #563 (got 13 columns instead of 12)
    Line #564 (got 13 columns instead of 12)
    Line #565 (got 13 columns instead of 12)
    Line #566 (got 13 columns instead of 12)
    Line #567 (got 13 columns instead of 12)
    Line #568 (got 13 columns instead of 12)
    Line #569 (got 13 columns instead of 12)
    Line #570 (got 13 columns instead of 12)
    Line #571 (got 13 columns instead of 12)
    Line #572 (got 13 columns instead of 12)
    Line #573 (got 13 columns instead of 12)
    Line #574 (got 13 columns instead of 12)
    Line #575 (got 13 columns instead of 12)
    Line #576 (got 13 columns instead of 12)
    Line #577 (got 13 columns instead of 12)
    Line #578 (got 13 columns instead of 12)
    Line #579 (got 13 columns instead of 12)
    Line #580 (got 13 columns instead of 12)
    Line #581 (got 13 columns instead of 12)
    Line #582 (got 13 columns instead of 12)
    Line #583 (got 13 columns instead of 12)
    Line #584 (got 13 columns instead of 12)
    Line #585 (got 13 columns instead of 12)
    Line #586 (got 13 columns instead of 12)
    Line #587 (got 13 columns instead of 12)
    Line #588 (got 13 columns instead of 12)
    Line #589 (got 13 columns instead of 12)
    Line #590 (got 13 columns instead of 12)
    Line #591 (got 13 columns instead of 12)
    Line #592 (got 13 columns instead of 12)
    Line #593 (got 13 columns instead of 12)
    Line #594 (got 13 columns instead of 12)
    Line #595 (got 13 columns instead of 12)
    Line #596 (got 13 columns instead of 12)
    Line #597 (got 13 columns instead of 12)
    Line #598 (got 13 columns instead of 12)
    Line #599 (got 13 columns instead of 12)
    Line #600 (got 13 columns instead of 12)
    Line #601 (got 13 columns instead of 12)
    Line #602 (got 13 columns instead of 12)
    Line #603 (got 13 columns instead of 12)
    Line #604 (got 13 columns instead of 12)
    Line #605 (got 13 columns instead of 12)
    Line #606 (got 13 columns instead of 12)
    Line #607 (got 13 columns instead of 12)
    Line #608 (got 13 columns instead of 12)
    Line #609 (got 13 columns instead of 12)
    Line #610 (got 13 columns instead of 12)
    Line #611 (got 13 columns instead of 12)
    Line #612 (got 13 columns instead of 12)
    Line #613 (got 13 columns instead of 12)
    Line #614 (got 13 columns instead of 12)
    Line #615 (got 13 columns instead of 12)
    Line #616 (got 13 columns instead of 12)
    Line #617 (got 13 columns instead of 12)
    Line #618 (got 13 columns instead of 12)
    Line #619 (got 13 columns instead of 12)
    Line #620 (got 13 columns instead of 12)
    Line #621 (got 13 columns instead of 12)
    Line #622 (got 13 columns instead of 12)
    Line #623 (got 13 columns instead of 12)
    Line #624 (got 13 columns instead of 12)
    Line #625 (got 13 columns instead of 12)
    Line #626 (got 13 columns instead of 12)
    Line #627 (got 13 columns instead of 12)
    Line #628 (got 13 columns instead of 12)
    Line #629 (got 13 columns instead of 12)
    Line #630 (got 13 columns instead of 12)
    Line #631 (got 13 columns instead of 12)
    Line #632 (got 13 columns instead of 12)
    Line #633 (got 13 columns instead of 12)
    Line #634 (got 13 columns instead of 12)
    Line #635 (got 13 columns instead of 12)
    Line #636 (got 13 columns instead of 12)
    Line #637 (got 13 columns instead of 12)
    Line #638 (got 13 columns instead of 12)
    Line #639 (got 13 columns instead of 12)
    Line #640 (got 13 columns instead of 12)
    Line #641 (got 13 columns instead of 12)
    Line #642 (got 13 columns instead of 12)
    Line #643 (got 13 columns instead of 12)
    Line #644 (got 13 columns instead of 12)
    Line #645 (got 13 columns instead of 12)
    Line #646 (got 13 columns instead of 12)
    Line #647 (got 13 columns instead of 12)
    Line #648 (got 13 columns instead of 12)
    Line #649 (got 13 columns instead of 12)
    Line #650 (got 13 columns instead of 12)
    Line #651 (got 13 columns instead of 12)
    Line #652 (got 13 columns instead of 12)
    Line #653 (got 13 columns instead of 12)
    Line #654 (got 13 columns instead of 12)
    Line #655 (got 13 columns instead of 12)
    Line #656 (got 13 columns instead of 12)
    Line #657 (got 13 columns instead of 12)
    Line #658 (got 13 columns instead of 12)
    Line #659 (got 13 columns instead of 12)
    Line #660 (got 13 columns instead of 12)
    Line #661 (got 13 columns instead of 12)
    Line #662 (got 13 columns instead of 12)
    Line #663 (got 13 columns instead of 12)
    Line #664 (got 13 columns instead of 12)
    Line #665 (got 13 columns instead of 12)
    Line #666 (got 13 columns instead of 12)
    Line #667 (got 13 columns instead of 12)
    Line #668 (got 13 columns instead of 12)
    Line #669 (got 13 columns instead of 12)
    Line #670 (got 13 columns instead of 12)
    Line #671 (got 13 columns instead of 12)
    Line #672 (got 13 columns instead of 12)
    Line #673 (got 13 columns instead of 12)
    Line #674 (got 13 columns instead of 12)
    Line #675 (got 13 columns instead of 12)
    Line #676 (got 13 columns instead of 12)
    Line #677 (got 13 columns instead of 12)
    Line #678 (got 13 columns instead of 12)
    Line #679 (got 13 columns instead of 12)
    Line #680 (got 13 columns instead of 12)
    Line #681 (got 13 columns instead of 12)
    Line #682 (got 13 columns instead of 12)
    Line #683 (got 13 columns instead of 12)
    Line #684 (got 13 columns instead of 12)
    Line #685 (got 13 columns instead of 12)
    Line #686 (got 13 columns instead of 12)
    Line #687 (got 13 columns instead of 12)
    Line #688 (got 13 columns instead of 12)
    Line #689 (got 13 columns instead of 12)
    Line #690 (got 13 columns instead of 12)
    Line #691 (got 13 columns instead of 12)
    Line #692 (got 13 columns instead of 12)
    Line #693 (got 13 columns instead of 12)
    Line #694 (got 13 columns instead of 12)
    Line #695 (got 13 columns instead of 12)
    Line #696 (got 13 columns instead of 12)
    Line #697 (got 13 columns instead of 12)
    Line #698 (got 13 columns instead of 12)
    Line #699 (got 13 columns instead of 12)
    Line #700 (got 13 columns instead of 12)
    Line #701 (got 13 columns instead of 12)
    Line #702 (got 13 columns instead of 12)
    Line #703 (got 13 columns instead of 12)
    Line #704 (got 13 columns instead of 12)
    Line #705 (got 13 columns instead of 12)
    Line #706 (got 13 columns instead of 12)
    Line #707 (got 13 columns instead of 12)
    Line #708 (got 13 columns instead of 12)
    Line #709 (got 13 columns instead of 12)
    Line #710 (got 13 columns instead of 12)
    Line #711 (got 13 columns instead of 12)
    Line #712 (got 13 columns instead of 12)
    Line #713 (got 13 columns instead of 12)
    Line #714 (got 13 columns instead of 12)
    Line #715 (got 13 columns instead of 12)
    Line #716 (got 13 columns instead of 12)
    Line #717 (got 13 columns instead of 12)
    Line #718 (got 13 columns instead of 12)
    Line #719 (got 13 columns instead of 12)
    Line #720 (got 13 columns instead of 12)
    Line #721 (got 13 columns instead of 12)
    Line #722 (got 13 columns instead of 12)
    Line #723 (got 13 columns instead of 12)
    Line #724 (got 13 columns instead of 12)
    Line #725 (got 13 columns instead of 12)
    Line #726 (got 13 columns instead of 12)
    Line #727 (got 13 columns instead of 12)
    Line #728 (got 13 columns instead of 12)
    Line #729 (got 13 columns instead of 12)
    Line #730 (got 13 columns instead of 12)
    Line #731 (got 13 columns instead of 12)
    Line #732 (got 13 columns instead of 12)
    Line #733 (got 13 columns instead of 12)
    Line #734 (got 13 columns instead of 12)
    Line #735 (got 13 columns instead of 12)
    Line #736 (got 13 columns instead of 12)
    Line #737 (got 13 columns instead of 12)
    Line #738 (got 13 columns instead of 12)
    Line #739 (got 13 columns instead of 12)
    Line #740 (got 13 columns instead of 12)
    Line #741 (got 13 columns instead of 12)
    Line #742 (got 13 columns instead of 12)
    Line #743 (got 13 columns instead of 12)
    Line #744 (got 13 columns instead of 12)
    Line #745 (got 13 columns instead of 12)
    Line #746 (got 13 columns instead of 12)
    Line #747 (got 13 columns instead of 12)
    Line #748 (got 13 columns instead of 12)
    Line #749 (got 13 columns instead of 12)
    Line #750 (got 13 columns instead of 12)
    Line #751 (got 13 columns instead of 12)
    Line #752 (got 13 columns instead of 12)
    Line #753 (got 13 columns instead of 12)
    Line #754 (got 13 columns instead of 12)
    Line #755 (got 13 columns instead of 12)
    Line #756 (got 13 columns instead of 12)
    Line #757 (got 13 columns instead of 12)
    Line #758 (got 13 columns instead of 12)
    Line #759 (got 13 columns instead of 12)
    Line #760 (got 13 columns instead of 12)
    Line #761 (got 13 columns instead of 12)
    Line #762 (got 13 columns instead of 12)
    Line #763 (got 13 columns instead of 12)
    Line #764 (got 13 columns instead of 12)
    Line #765 (got 13 columns instead of 12)
    Line #766 (got 13 columns instead of 12)
    Line #767 (got 13 columns instead of 12)
    Line #768 (got 13 columns instead of 12)
    Line #769 (got 13 columns instead of 12)
    Line #770 (got 13 columns instead of 12)
    Line #771 (got 13 columns instead of 12)
    Line #772 (got 13 columns instead of 12)
    Line #773 (got 13 columns instead of 12)
    Line #774 (got 13 columns instead of 12)
    Line #775 (got 13 columns instead of 12)
    Line #776 (got 13 columns instead of 12)
    Line #777 (got 13 columns instead of 12)
    Line #778 (got 13 columns instead of 12)
    Line #779 (got 13 columns instead of 12)
    Line #780 (got 13 columns instead of 12)
    Line #781 (got 13 columns instead of 12)
    Line #782 (got 13 columns instead of 12)
    Line #783 (got 13 columns instead of 12)
    Line #784 (got 13 columns instead of 12)
    Line #785 (got 13 columns instead of 12)
    Line #786 (got 13 columns instead of 12)
    Line #787 (got 13 columns instead of 12)
    Line #788 (got 13 columns instead of 12)
    Line #789 (got 13 columns instead of 12)
    Line #790 (got 13 columns instead of 12)
    Line #791 (got 13 columns instead of 12)
    Line #792 (got 13 columns instead of 12)
    Line #793 (got 13 columns instead of 12)
    Line #794 (got 13 columns instead of 12)
    Line #795 (got 13 columns instead of 12)
    Line #796 (got 13 columns instead of 12)
    Line #797 (got 13 columns instead of 12)
    Line #798 (got 13 columns instead of 12)
    Line #799 (got 13 columns instead of 12)
    Line #800 (got 13 columns instead of 12)
    Line #801 (got 13 columns instead of 12)
    Line #802 (got 13 columns instead of 12)
    Line #803 (got 13 columns instead of 12)
    Line #804 (got 13 columns instead of 12)
    Line #805 (got 13 columns instead of 12)
    Line #806 (got 13 columns instead of 12)
    Line #807 (got 13 columns instead of 12)
    Line #808 (got 13 columns instead of 12)
    Line #809 (got 13 columns instead of 12)
    Line #810 (got 13 columns instead of 12)
    Line #811 (got 13 columns instead of 12)
    Line #812 (got 13 columns instead of 12)
    Line #813 (got 13 columns instead of 12)
    Line #814 (got 13 columns instead of 12)
    Line #815 (got 13 columns instead of 12)
    Line #816 (got 13 columns instead of 12)
    Line #817 (got 13 columns instead of 12)
    Line #818 (got 13 columns instead of 12)
    Line #819 (got 13 columns instead of 12)
    Line #820 (got 13 columns instead of 12)
    Line #821 (got 13 columns instead of 12)
    Line #822 (got 13 columns instead of 12)
    Line #823 (got 13 columns instead of 12)
    Line #824 (got 13 columns instead of 12)
    Line #825 (got 13 columns instead of 12)
    Line #826 (got 13 columns instead of 12)
    Line #827 (got 13 columns instead of 12)
    Line #828 (got 13 columns instead of 12)
    Line #829 (got 13 columns instead of 12)
    Line #830 (got 13 columns instead of 12)
    Line #831 (got 13 columns instead of 12)
    Line #832 (got 13 columns instead of 12)
    Line #833 (got 13 columns instead of 12)
    Line #834 (got 13 columns instead of 12)
    Line #835 (got 13 columns instead of 12)
    Line #836 (got 13 columns instead of 12)
    Line #837 (got 13 columns instead of 12)
    Line #838 (got 13 columns instead of 12)
    Line #839 (got 13 columns instead of 12)
    Line #840 (got 13 columns instead of 12)
    Line #841 (got 13 columns instead of 12)
    Line #842 (got 13 columns instead of 12)
    Line #843 (got 13 columns instead of 12)
    Line #844 (got 13 columns instead of 12)
    Line #845 (got 13 columns instead of 12)
    Line #846 (got 13 columns instead of 12)
    Line #847 (got 13 columns instead of 12)
    Line #848 (got 13 columns instead of 12)
    Line #849 (got 13 columns instead of 12)
    Line #850 (got 13 columns instead of 12)
    Line #851 (got 13 columns instead of 12)
    Line #852 (got 13 columns instead of 12)
    Line #853 (got 13 columns instead of 12)
    Line #854 (got 13 columns instead of 12)
    Line #855 (got 13 columns instead of 12)
    Line #856 (got 13 columns instead of 12)
    Line #857 (got 13 columns instead of 12)
    Line #858 (got 13 columns instead of 12)
    Line #859 (got 13 columns instead of 12)
    Line #860 (got 13 columns instead of 12)
    Line #861 (got 13 columns instead of 12)
    Line #862 (got 13 columns instead of 12)
    Line #863 (got 13 columns instead of 12)
    Line #864 (got 13 columns instead of 12)
    Line #865 (got 13 columns instead of 12)
    Line #866 (got 13 columns instead of 12)
    Line #867 (got 13 columns instead of 12)
    Line #868 (got 13 columns instead of 12)
    Line #869 (got 13 columns instead of 12)
    Line #870 (got 13 columns instead of 12)
    Line #871 (got 13 columns instead of 12)
    Line #872 (got 13 columns instead of 12)
    Line #873 (got 13 columns instead of 12)
    Line #874 (got 13 columns instead of 12)
    Line #875 (got 13 columns instead of 12)
    Line #876 (got 13 columns instead of 12)
    Line #877 (got 13 columns instead of 12)
    Line #878 (got 13 columns instead of 12)
    Line #879 (got 13 columns instead of 12)
    Line #880 (got 13 columns instead of 12)
    Line #881 (got 13 columns instead of 12)
    Line #882 (got 13 columns instead of 12)
    Line #883 (got 13 columns instead of 12)
    Line #884 (got 13 columns instead of 12)
    Line #885 (got 13 columns instead of 12)
    Line #886 (got 13 columns instead of 12)
    Line #887 (got 13 columns instead of 12)
    Line #888 (got 13 columns instead of 12)
    Line #889 (got 13 columns instead of 12)
    Line #890 (got 13 columns instead of 12)
    Line #891 (got 13 columns instead of 12)
    Line #892 (got 13 columns instead of 12)