In [1]:
i = 10

In [2]:
a = 5

In [3]:
a * i

50

In [4]:
a * a

25

In [5]:
i = 7

In [6]:
a * i

35

In [7]:
x = 10

In [8]:
X = 5

In [9]:
print(x)

10


In [10]:
print(X)

5


In [11]:
x*X

50

In [12]:
x = 0

In [13]:
x*x + 3*x + 40

40

In [14]:
x = 5

In [15]:
x*x + 3*x + 40

80

In [16]:
import numpy as np
## SHIFT+ENTER

In [17]:
a = np.array([1.0,2.0,3])

In [18]:
a

array([1., 2., 3.])

In [19]:
type(a)

numpy.ndarray

In [20]:
a.dtype

dtype('float64')

In [21]:
a.ndim

1

In [22]:
a = np.arange(15).reshape(3, 5)

In [23]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
a.ndim

2

In [25]:
a.size

15

In [26]:
a.shape

(3, 5)

In [27]:
a.dtype

dtype('int64')

In [28]:
a.itemsize

8

In [29]:
b = np.array(['xyz','wery'])

In [30]:
b

array(['xyz', 'wery'], dtype='<U4')

In [31]:
b.dtype

dtype('<U4')

In [32]:
b.dtype.name

'str128'

In [33]:
c = np.array([1,2,3], dtype=complex)

In [34]:
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [35]:
c.dtype

dtype('complex128')

In [36]:
c.dtype.name

'complex128'

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.zeros((3,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
d = np.ones((4,4))

In [42]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
d.dtype

dtype('float64')

In [44]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
x = np.arange(0,10,0.2)

In [48]:
x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [49]:
x.dtype

dtype('float64')

In [50]:
x = np.arange(0,10)

In [51]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
x+4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [53]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [54]:
y = x + 5

In [55]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
y

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
z = x+y

In [58]:
z

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [59]:
np.sqrt(y)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [60]:
z = x + np.sqrt(y)

In [61]:
z

array([ 2.23606798,  3.44948974,  4.64575131,  5.82842712,  7.        ,
        8.16227766,  9.31662479, 10.46410162, 11.60555128, 12.74165739])

In [62]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.dot(x,z)

435.7054487727669

In [64]:
x.dot(z)

435.7054487727669

In [65]:
z.dot(x)

435.7054487727669

In [66]:
z

array([ 2.23606798,  3.44948974,  4.64575131,  5.82842712,  7.        ,
        8.16227766,  9.31662479, 10.46410162, 11.60555128, 12.74165739])

In [67]:
x += 1

In [68]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
x -=1

In [70]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x *=2

In [72]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [73]:
x + 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [74]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [75]:
y = np.sqrt(x)

In [76]:
y

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

In [77]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
np.log(x+1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])

In [79]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [80]:
a.sum()

105

In [81]:
a.min()

0

In [82]:
x += 1

In [83]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [84]:
x.min()

1

In [85]:
np.sin(x)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [86]:
np.sin(x)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [87]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [88]:
x.max()

19

In [89]:
x.mean()

10.0

In [90]:
x.std()

5.744562646538029

In [91]:
a = np.arange(10,16)

In [92]:
a

array([10, 11, 12, 13, 14, 15])

In [93]:
a[0]

10

In [94]:
a[1]

11

In [95]:
a[4]

14

In [96]:
a[-1]

15

In [97]:
a[0]

10

In [98]:
a

array([10, 11, 12, 13, 14, 15])

In [99]:
a = np.arange(10)

In [100]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
a = np.sqrt(a)

In [102]:
a

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [103]:
a = np.arange(87)

In [104]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86])

In [105]:
a[-1]

86

In [106]:
a[-2]

85

In [107]:
a[[1,3,4]]

array([1, 3, 4])

In [108]:
a[[0,-1]]

array([ 0, 86])

In [109]:
a[[11,13,-2]]

array([11, 13, 85])

In [110]:
a[[11,13,-1]]

array([11, 13, 86])

In [111]:
a[[11,13,-2,86]]

array([11, 13, 85, 86])

In [112]:
a = np.arange(9).reshape(3,3)

In [113]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [114]:
a[1,2]

5

In [115]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
a[2,2]

8

In [117]:
a[0,0]

0

In [118]:
a[1,1]

4

In [119]:
a[11]

IndexError: index 11 is out of bounds for axis 0 with size 3

In [ ]:
a[1]

In [ ]:
a[0]

In [ ]:
a = np.arange(16)

In [ ]:
a

In [ ]:
a[[6,7,8,9,10]]

In [ ]:
a  = np.arange(99)

In [ ]:
a

In [ ]:
a[22:88]

In [ ]:
a += 1

In [ ]:
a

In [ ]:
a[22:88]

In [ ]:
a[22:88:92]

In [ ]:
a[22:88:2]

In [ ]:
a[22:88:1]

In [ ]:
a[22:88:-1]

In [ ]:
a[22:88:1]

In [ ]:
a[22:88:2]

In [ ]:
a[22:88:3]

In [ ]:
a[22:88:10]

In [ ]:
a = np.arange(100,200)

In [ ]:
a

In [ ]:
a[22:88:10]

In [ ]:
a[22:88:-1]

In [ ]:
a[88:22:-1]

In [ ]:
a[::1]

In [ ]:
a[::2]

In [ ]:
a[:5:]

In [ ]:
a = np.arange(10,19).reshape(3,3)

In [ ]:
a

In [ ]:
a[0]

In [ ]:
a[1]

In [ ]:
a[2]

In [ ]:
a[0,:]

In [ ]:
a[:,0]

In [ ]:
a[:,1]

In [ ]:
a

In [ ]:
a[0:1,0:1]

In [ ]:
a[0:1,0:2]

In [ ]:
a[0:2,0:2]

In [ ]:
a[[0,2],0:2]

In [ ]:
a

In [ ]:
for i in a :
    print(i)
    print("---")

In [ ]:
a.flat

In [ ]:
for item in a.flat:
    print(item)
    print("-----")

In [120]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [121]:
np.apply_along_axis(np.mean,axis=0,arr=a)

array([3., 4., 5.])

In [122]:
np.apply_along_axis(np.mean,axis=1,arr=a)

array([1., 4., 7.])

In [123]:
def halfOfValue(x):
    return x/2


In [124]:
np.apply_along_axis(halfOfValue,axis=0,arr=a)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [125]:
np.apply_along_axis(halfOfValue,axis=1,arr=a)

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [126]:
def doubleOfValue(x):
    return 2*x


In [127]:
np.apply_along_axis(doubleOfValue,axis=1,arr=a)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [128]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
def substractOne(x):
    return x-1

In [130]:
np.apply_along_axis(substractOne,axis=0,arr=a)

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [131]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [132]:
a[0]

array([0, 1, 2])

In [133]:
a = np.random.random((4,4))

In [134]:
a

array([[0.92901327, 0.71094459, 0.01735287, 0.37693376],
       [0.47271295, 0.91222211, 0.84010164, 0.66262554],
       [0.36204628, 0.81077851, 0.75791578, 0.99341958],
       [0.02372879, 0.24247506, 0.59590525, 0.20643598]])

In [135]:
a < 0.5

array([[False, False,  True,  True],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True,  True, False,  True]])

In [136]:
b = a < 0.5

In [137]:
b

array([[False, False,  True,  True],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True,  True, False,  True]])

In [138]:
c = a > 0.6

In [139]:
c

array([[ True,  True, False, False],
       [False,  True,  True,  True],
       [False,  True,  True,  True],
       [False, False, False, False]])

In [140]:
c.dtype

dtype('bool')

In [141]:
b = a[a < 0.5]

In [142]:
b

array([0.01735287, 0.37693376, 0.47271295, 0.36204628, 0.02372879,
       0.24247506, 0.20643598])

In [143]:
a

array([[0.92901327, 0.71094459, 0.01735287, 0.37693376],
       [0.47271295, 0.91222211, 0.84010164, 0.66262554],
       [0.36204628, 0.81077851, 0.75791578, 0.99341958],
       [0.02372879, 0.24247506, 0.59590525, 0.20643598]])

In [144]:
b = a[a > 0.5]

In [145]:
b

array([0.92901327, 0.71094459, 0.91222211, 0.84010164, 0.66262554,
       0.81077851, 0.75791578, 0.99341958, 0.59590525])

In [158]:
a = np.random.random((4,4))

In [159]:
b

array([0.78012206, 0.93674955, 0.78827182, 0.83340097, 0.53666861,
       0.50595173])

In [160]:
a

array([[0.79078663, 0.49505892, 0.20818806, 0.06264601],
       [0.63364027, 0.81413481, 0.63902849, 0.14494608],
       [0.42091761, 0.15305952, 0.7812497 , 0.74273315],
       [0.75385417, 0.2668867 , 0.72342004, 0.31139823]])

In [154]:
b = a[a > 0.5]

In [167]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
        0.96400068],
       [0.23659126, 0.04740352, 0.06892495, 0.7434043 , 0.11450833,
        0.07771495]])

In [156]:
b

array([0.78012206, 0.93674955, 0.78827182, 0.83340097, 0.53666861,
       0.50595173])

In [161]:
a = np.random.random(12)

In [162]:
a

array([0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
       0.96400068, 0.23659126, 0.04740352, 0.06892495, 0.7434043 ,
       0.11450833, 0.07771495])

In [165]:
a = a.reshape(2,6)

In [166]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
        0.96400068],
       [0.23659126, 0.04740352, 0.06892495, 0.7434043 , 0.11450833,
        0.07771495]])

In [169]:
a.shape = (3,4)

In [170]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598],
       [0.94090523, 0.96400068, 0.23659126, 0.04740352],
       [0.06892495, 0.7434043 , 0.11450833, 0.07771495]])

In [171]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598],
       [0.94090523, 0.96400068, 0.23659126, 0.04740352],
       [0.06892495, 0.7434043 , 0.11450833, 0.07771495]])

In [172]:
a.ravel()

array([0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
       0.96400068, 0.23659126, 0.04740352, 0.06892495, 0.7434043 ,
       0.11450833, 0.07771495])

In [173]:
b = a

In [174]:
b

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598],
       [0.94090523, 0.96400068, 0.23659126, 0.04740352],
       [0.06892495, 0.7434043 , 0.11450833, 0.07771495]])

In [175]:
b.shape = (12)

In [176]:
b

array([0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
       0.96400068, 0.23659126, 0.04740352, 0.06892495, 0.7434043 ,
       0.11450833, 0.07771495])

In [177]:
a

array([0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
       0.96400068, 0.23659126, 0.04740352, 0.06892495, 0.7434043 ,
       0.11450833, 0.07771495])

In [178]:
a.transpose()

array([0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
       0.96400068, 0.23659126, 0.04740352, 0.06892495, 0.7434043 ,
       0.11450833, 0.07771495])

In [179]:
a.shape = (2,6)

In [180]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
        0.96400068],
       [0.23659126, 0.04740352, 0.06892495, 0.7434043 , 0.11450833,
        0.07771495]])

In [183]:
b = a.transpose()

In [184]:
a

array([[0.09174265, 0.89005504, 0.74979389, 0.28681598, 0.94090523,
        0.96400068],
       [0.23659126, 0.04740352, 0.06892495, 0.7434043 , 0.11450833,
        0.07771495]])

In [185]:
b

array([[0.09174265, 0.23659126],
       [0.89005504, 0.04740352],
       [0.74979389, 0.06892495],
       [0.28681598, 0.7434043 ],
       [0.94090523, 0.11450833],
       [0.96400068, 0.07771495]])

In [186]:
a = np.ones((3,3))

In [187]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [188]:
b = np.zeros((3,3))

In [189]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [190]:
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [191]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [192]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [193]:
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [194]:
a = np.arange(16).reshape((4,4))

In [195]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [196]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [197]:
[b,c] = np.hsplit(a,2)

In [198]:
b

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [199]:
c

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [200]:
[b,c] = np.vsplit(a,2)

In [201]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [202]:
c

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [203]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [204]:
b = a

In [205]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [206]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [211]:
b = np.arange(16)

In [208]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [209]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [210]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [212]:
c = a

In [213]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [214]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [215]:
c.shape = (2,8)

In [216]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [217]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [218]:
a.shape=(4,4)

In [219]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [220]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [221]:
c = a.copy()

In [222]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [223]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [224]:
c.shape = (2,8)

In [225]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [226]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [227]:
a.shape=(8,2)

In [228]:
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [229]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [230]:
a 

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [231]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [232]:
a.shape = (4,4)

In [233]:
c.shape = (4,4)

In [234]:
a * c

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [235]:
a = np.arange(16).reshape(4,4)

In [236]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [237]:
b = np.arange(4)

In [239]:
b

array([0, 1, 2, 3])

In [240]:
a * b

array([[ 0,  1,  4,  9],
       [ 0,  5, 12, 21],
       [ 0,  9, 20, 33],
       [ 0, 13, 28, 45]])

In [241]:
a + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [242]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [243]:
b

array([0, 1, 2, 3])

In [244]:
a = np.arange(6).reshape(3,1,2)

In [245]:
a

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [246]:
b = np.arange(6).reshape(3,2,1)

In [247]:
b

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [248]:
a + b

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

In [275]:
a = np.array([(1,'First', 0.2,1+2j),(2,'Second', 0.4,1-2j),(3,'Third', 0.3,3+2j)],
             dtype=[('id','i2'),('position','a6'),('value','f4'),('complex','c8')])

In [276]:
a

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (3, b'Third', 0.3, 3.+2.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [265]:
a[0]

(1, b'First', 0.2, 1.+2.j)

In [266]:
a[1]

(2, b'Second', 0.4, 1.-2.j)

In [267]:
a[2]

(3, b'Third', 0.3, 3.+2.j)

In [268]:
a[0]

(1, b'First', 0.2, 1.+2.j)

In [270]:
a['id']

array([1, 2, 3], dtype=int16)

In [272]:
a['position']

array([b'First', b'Second', b'Third'], dtype='|S6')

In [273]:
a['value']

array([0.2, 0.4, 0.3], dtype=float32)

In [274]:
a['complex']

array([1.+2.j, 1.-2.j, 3.+2.j], dtype=complex64)

In [279]:
a.dtype.names=('idx','order','valuex','cplx')

In [280]:
a

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (3, b'Third', 0.3, 3.+2.j)],
      dtype=[('idx', '<i2'), ('order', 'S6'), ('valuex', '<f4'), ('cplx', '<c8')])

In [281]:
a

array([(1, b'First', 0.2, 1.+2.j), (2, b'Second', 0.4, 1.-2.j),
       (3, b'Third', 0.3, 3.+2.j)],
      dtype=[('idx', '<i2'), ('order', 'S6'), ('valuex', '<f4'), ('cplx', '<c8')])

In [283]:
np.save('saved_data',a)

In [ ]:
data = np.load(saved_data.n)