In [1]:
i = 10

In [2]:
a = 5

In [3]:
a * i

50

In [4]:
a * a

25

In [5]:
i = 7

In [6]:
a * i

35

In [8]:
x = 10

In [10]:
X = 5

In [12]:
print(x)

10


In [13]:
print(X)

5


In [14]:
x*X

50

In [19]:
x = 0

In [20]:
x*x + 3*x + 40

40

In [22]:
x = 5

In [23]:
x*x + 3*x + 40

80

In [40]:
import numpy as np
## SHIFT+ENTER

In [41]:
a = np.array([1.0,2.0,3])

In [42]:
a

array([1., 2., 3.])

In [43]:
type(a)

numpy.ndarray

In [44]:
a.dtype

dtype('float64')

In [45]:
a.ndim

1

In [46]:
a = np.arange(15).reshape(3, 5)

In [47]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
a.ndim

2

In [49]:
a.size

15

In [50]:
a.shape

(3, 5)

In [51]:
a.dtype

dtype('int64')

In [52]:
a.itemsize

8

In [55]:
b = np.array(['xyz','wery'])

In [56]:
b

array(['xyz', 'wery'], dtype='<U4')

In [57]:
b.dtype

dtype('<U4')

In [58]:
b.dtype.name

'str128'

In [70]:
c = np.array([1,2,3], dtype=complex)

In [60]:
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [61]:
c.dtype

dtype('complex128')

In [62]:
c.dtype.name

'complex128'

In [63]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
np.zeros((3,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [66]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
d = np.ones((4,4))

In [68]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
d.dtype

dtype('float64')

In [72]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
x = np.arange(0,10,0.2)

In [83]:
x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [84]:
x.dtype

dtype('float64')

In [86]:
x = np.arange(0,10)

In [87]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
x+4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [89]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
y = x + 5

In [91]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
y

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [93]:
z = x+y

In [94]:
z

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [95]:
np.sqrt(y)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [96]:
z = x + np.sqrt(y)

In [97]:
z

array([ 2.23606798,  3.44948974,  4.64575131,  5.82842712,  7.        ,
        8.16227766,  9.31662479, 10.46410162, 11.60555128, 12.74165739])