In [128]:
i = 10

In [129]:
a = 5

In [130]:
a * i

50

In [131]:
a * a

25

In [132]:
i = 7

In [133]:
a * i

35

In [134]:
x = 10

In [135]:
X = 5

In [136]:
print(x)

10


In [137]:
print(X)

5


In [138]:
x*X

50

In [139]:
x = 0

In [140]:
x*x + 3*x + 40

40

In [141]:
x = 5

In [142]:
x*x + 3*x + 40

80

In [143]:
import numpy as np
## SHIFT+ENTER

In [144]:
a = np.array([1.0,2.0,3])

In [145]:
a

array([1., 2., 3.])

In [146]:
type(a)

numpy.ndarray

In [147]:
a.dtype

dtype('float64')

In [148]:
a.ndim

1

In [149]:
a = np.arange(15).reshape(3, 5)

In [150]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [151]:
a.ndim

2

In [152]:
a.size

15

In [153]:
a.shape

(3, 5)

In [154]:
a.dtype

dtype('int64')

In [155]:
a.itemsize

8

In [156]:
b = np.array(['xyz','wery'])

In [157]:
b

array(['xyz', 'wery'], dtype='<U4')

In [158]:
b.dtype

dtype('<U4')

In [159]:
b.dtype.name

'str128'

In [160]:
c = np.array([1,2,3], dtype=complex)

In [161]:
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [162]:
c.dtype

dtype('complex128')

In [163]:
c.dtype.name

'complex128'

In [164]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [165]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [166]:
np.zeros((3,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [167]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [168]:
d = np.ones((4,4))

In [169]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [170]:
d.dtype

dtype('float64')

In [171]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [173]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [174]:
x = np.arange(0,10,0.2)

In [175]:
x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [176]:
x.dtype

dtype('float64')

In [177]:
x = np.arange(0,10)

In [178]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
x+4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [180]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [181]:
y = x + 5

In [182]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
y

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [184]:
z = x+y

In [185]:
z

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [186]:
np.sqrt(y)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [187]:
z = x + np.sqrt(y)

In [188]:
z

array([ 2.23606798,  3.44948974,  4.64575131,  5.82842712,  7.        ,
        8.16227766,  9.31662479, 10.46410162, 11.60555128, 12.74165739])

In [189]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
np.dot(x,z)

435.7054487727669

In [191]:
x.dot(z)

435.7054487727669

In [192]:
z.dot(x)

435.7054487727669

In [193]:
z

array([ 2.23606798,  3.44948974,  4.64575131,  5.82842712,  7.        ,
        8.16227766,  9.31662479, 10.46410162, 11.60555128, 12.74165739])

In [194]:
x += 1

In [195]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [196]:
x -=1

In [197]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [198]:
x *=2

In [199]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [200]:
x + 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [201]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [202]:
y = np.sqrt(x)

In [203]:
y

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

In [204]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [205]:
np.log(x+1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])

In [206]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [207]:
a.sum()

105

In [208]:
a.min()

0

In [209]:
x += 1

In [210]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [211]:
x.min()

1

In [212]:
np.sin(x)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [213]:
np.sin(x)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [214]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [215]:
x.max()

19

In [216]:
x.mean()

10.0

In [217]:
x.std()

5.744562646538029

In [218]:
a = np.arange(10,16)

In [219]:
a

array([10, 11, 12, 13, 14, 15])

In [220]:
a[0]

10

In [221]:
a[1]

11

In [222]:
a[4]

14

In [223]:
a[-1]

15

In [224]:
a[0]

10

In [225]:
a

array([10, 11, 12, 13, 14, 15])

In [226]:
a = np.arange(10)

In [227]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [228]:
a = np.sqrt(a)

In [229]:
a

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [230]:
a = np.arange(87)

In [231]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86])

In [232]:
a[-1]

86

In [233]:
a[-2]

85

In [234]:
a[[1,3,4]]

array([1, 3, 4])

In [235]:
a[[0,-1]]

array([ 0, 86])

In [236]:
a[[11,13,-2]]

array([11, 13, 85])

In [237]:
a[[11,13,-1]]

array([11, 13, 86])

In [238]:
a[[11,13,-2,86]]

array([11, 13, 85, 86])

In [239]:
a = np.arange(9).reshape(3,3)

In [240]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [241]:
a[1,2]

5

In [242]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [243]:
a[2,2]

8

In [244]:
a[0,0]

0

In [245]:
a[1,1]

4

In [246]:
a[11]

IndexError: index 11 is out of bounds for axis 0 with size 3

In [ ]:
a[1]

In [ ]:
a[0]

In [ ]:
a = np.arange(16)

In [ ]:
a

In [ ]:
a[[6,7,8,9,10]]

In [ ]:
a  = np.arange(99)

In [ ]:
a

In [ ]:
a[22:88]

In [ ]:
a += 1

In [ ]:
a

In [ ]:
a[22:88]

In [ ]:
a[22:88:92]

In [ ]:
a[22:88:2]

In [ ]:
a[22:88:1]

In [ ]:
a[22:88:-1]

In [ ]:
a[22:88:1]

In [ ]:
a[22:88:2]

In [ ]:
a[22:88:3]

In [ ]:
a[22:88:10]

In [ ]:
a = np.arange(100,200)

In [ ]:
a

In [ ]:
a[22:88:10]

In [ ]:
a[22:88:-1]

In [ ]:
a[88:22:-1]

In [ ]:
a[::1]

In [ ]:
a[::2]

In [ ]:
a[:5:]

In [ ]:
a = np.arange(10,19).reshape(3,3)

In [ ]:
a

In [ ]:
a[0]

In [ ]:
a[1]

In [ ]:
a[2]

In [ ]:
a[0,:]

In [ ]:
a[:,0]

In [ ]:
a[:,1]

In [ ]:
a

In [ ]:
a[0:1,0:1]

In [ ]:
a[0:1,0:2]

In [ ]:
a[0:2,0:2]

In [ ]:
a[[0,2],0:2]

In [ ]:
a

In [ ]:
for i in a :
    print(i)
    print("---")

In [ ]:
a.flat

In [ ]:
for item in a.flat:
    print(item)
    print("-----")

In [ ]:
a

In [ ]:
np.apply_along_axis(np.mean,axis=0,arr=a)

In [ ]:
np.apply_along_axis(np.mean,axis=1,arr=a)

In [ ]:
def halfOfValue(x):
    return x/2


In [ ]:
np.apply_along_axis(halfOfValue,axis=0,arr=a)

In [ ]:
np.apply_along_axis(halfOfValue,axis=1,arr=a)

In [ ]:
def doubleOfValue(x):
    return 2*x


In [ ]:
np.apply_along_axis(doubleOfValue,axis=1,arr=a)

In [ ]:
a

In [ ]:
def substractOne(x):
    return x-1

In [ ]:
np.apply_along_axis(substractOne,axis=0,arr=a)

In [ ]:
a

In [ ]:
a[0]

In [ ]:
a = np.random.random((4,4))

In [ ]:
a

In [ ]:
a < 0.5

In [ ]:
b = a < 0.5

In [ ]:
b

In [ ]:
c = a > 0.6

In [ ]:
c

In [ ]:
c.dtype

In [ ]:
b = a[a < 0.5]

In [ ]:
b

In [ ]:
a

In [ ]:
b = a[a > 0.5]

In [ ]:
b

In [ ]:
a = np.random.random((4,4))

In [ ]:
b

In [ ]:
a

In [ ]:
b = a[a > 0.5]

In [ ]:
a

In [ ]:
b

In [ ]:
a = np.random.random(12)

In [ ]:
a

In [ ]:
a = a.reshape(2,6)

In [ ]:
a

In [ ]:
a.shape = (3,4)

In [ ]:
a

In [ ]:
a

In [ ]:
a.ravel()

In [ ]:
b = a

In [ ]:
b

In [ ]:
b.shape = (12)

In [ ]:
b

In [ ]:
a

In [ ]:
a.transpose()

In [ ]:
a.shape = (2,6)

In [ ]:
a

In [ ]:
b = a.transpose()

In [ ]:
a

In [ ]:
b

In [ ]:
a = np.ones((3,3))

In [ ]:
a

In [ ]:
b = np.zeros((3,3))

In [ ]:
b

In [ ]:
np.vstack((a,b))

In [ ]:
a

In [ ]:
b

In [ ]:
np.hstack((a,b))

In [ ]:
a = np.arange(16).reshape((4,4))

In [ ]:
a

In [ ]:
np.hsplit(a,2)

In [ ]:
[b,c] = np.hsplit(a,2)

In [ ]:
b

In [ ]:
c

In [ ]:
[b,c] = np.vsplit(a,2)

In [ ]:
b

In [ ]:
c

In [ ]:
a

In [ ]:
b = a

In [ ]:
b

In [ ]:
a

In [ ]:
b = np.arange(16)

In [ ]:
b

In [ ]:
a

In [ ]:
a

In [ ]:
c = a

In [ ]:
c

In [ ]:
a

In [ ]:
c.shape = (2,8)

In [ ]:
c

In [ ]:
a

In [ ]:
a.shape=(4,4)

In [ ]:
a

In [ ]:
c

In [ ]:
c = a.copy()

In [ ]:
c

In [ ]:
a

In [ ]:
c.shape = (2,8)

In [ ]:
c

In [ ]:
a

In [ ]:
a.shape=(8,2)

In [ ]:
a

In [ ]:
c

In [ ]:
a 

In [ ]:
c

In [ ]:
a.shape = (4,4)

In [ ]:
c.shape = (4,4)

In [ ]:
a * c

In [ ]:
a = np.arange(16).reshape(4,4)

In [ ]:
a

In [ ]:
b = np.arange(4)

In [ ]:
b

In [ ]:
a * b

In [ ]:
a + b

In [ ]:
a

In [ ]:
b

In [ ]:
a = np.arange(6).reshape(3,1,2)

In [ ]:
a

In [ ]:
b = np.arange(6).reshape(3,2,1)

In [ ]:
b

In [ ]:
a + b

In [ ]:
a = np.array([(1,"First", 0.2,1+2j),(2,'Second', 0.4,1-2j),(3,'Third', 0.3,3+2j)],
             dtype=[('id','i2'),('position','S6'),('value','f4'),('complex','c8')])

In [ ]:
a

In [ ]:
a[0]

In [ ]:
a[1]

In [ ]:
a[2]

In [ ]:
a[0]

In [ ]:
a['id']

In [ ]:
a['position']

In [ ]:
a['value']

In [ ]:
a['complex']

In [ ]:
a.dtype.names=('idx','order','valuex','cplx')

In [ ]:
a

In [ ]:
a

In [ ]:
np.save('saved_data',a)

In [ ]:
data = np.load('saved_data.npy')

In [ ]:
data

In [247]:
data = np.genfromtxt('02_data.csv',delimiter=',',names=True)

In [248]:
data

array([(1., nan, 34.), (2., nan, 56.), (3., nan, 96.)],
      dtype=[('id', '<f8'), ('position', '<f8'), ('value', '<f8')])

In [ ]:
data['id']

In [ ]:
data[0]

In [ ]:
data[1]

In [ ]:
b = "xxxxx"

In [249]:
data = np.genfromtxt('02_data.csv',delimiter=',',names=True, dtype=None,encoding="UTF-8")

In [250]:
data

array([(1, 'First', 34), (2, 'Second', 56), (3, 'Three', 96)],
      dtype=[('id', '<i8'), ('position', '<U6'), ('value', '<i8')])

In [254]:
data = np.genfromtxt('02_data.csv',delimiter=',',names=True, dtype=(int,'U8',int),encoding="UTF-8")
data

array([(1, 'First', 34), (2, 'Second', 56), (3, 'Three', 96)],
      dtype=[('id', '<i8'), ('position', '<U8'), ('value', '<i8')])

In [ ]:
b = np.array(['a','ccc'])

In [255]:
b

array(['xyz', 'wery'], dtype='<U4')

In [256]:
b[0]

'xyz'

In [257]:
b[1]

'wery'