In [6]:
i = 10

In [7]:
a = 5

In [8]:
a * i

50

In [9]:
a * a

25

In [10]:
i = 7

In [11]:
a * i

35

In [12]:
x = 10

In [13]:
X = 5

In [14]:
print(x)

10


In [15]:
print(X)

5


In [16]:
x*X

50

In [17]:
x = 0

In [18]:
x*x + 3*x + 40

40

In [19]:
x = 5

In [20]:
x*x + 3*x + 40

80

In [21]:
import numpy as np
## SHIFT+ENTER

In [22]:
a = np.array([1.0,2.0,3])

In [23]:
a

array([1., 2., 3.])

In [24]:
type(a)

numpy.ndarray

In [25]:
a.dtype

dtype('float64')

In [26]:
a.ndim

1

In [27]:
a = np.arange(15).reshape(3, 5)

In [28]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
a.ndim

2

In [30]:
a.size

15

In [31]:
a.shape

(3, 5)

In [32]:
a.dtype

dtype('int64')

In [33]:
a.itemsize

8

In [34]:
b = np.array(['xyz','wery'])

In [35]:
b

array(['xyz', 'wery'], dtype='<U4')

In [36]:
b.dtype

dtype('<U4')

In [37]:
b.dtype.name

'str128'

In [38]:
c = np.array([1,2,3], dtype=complex)

In [39]:
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [40]:
c.dtype

dtype('complex128')

In [41]:
c.dtype.name

'complex128'

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.zeros((3,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
d = np.ones((4,4))

In [47]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
d.dtype

dtype('float64')

In [49]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
x = np.arange(0,10,0.2)

In [53]:
x

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [54]:
x.dtype

dtype('float64')

In [55]:
x = np.arange(0,10)

In [56]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
x+4

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [58]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
y = x + 5

In [60]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
y

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
z = x+y

In [63]:
z

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [64]:
np.sqrt(y)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [65]:
z = x + np.sqrt(y)

In [67]:
z

array([ 2.23606798,  3.44948974,  4.64575131,  5.82842712,  7.        ,
        8.16227766,  9.31662479, 10.46410162, 11.60555128, 12.74165739])

In [68]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.dot(x,z)

435.7054487727669

In [70]:
x.dot(z)

435.7054487727669

In [71]:
z.dot(x)

435.7054487727669

In [81]:
z

array([ 2.23606798,  3.44948974,  4.64575131,  5.82842712,  7.        ,
        8.16227766,  9.31662479, 10.46410162, 11.60555128, 12.74165739])

In [73]:
x += 1

In [74]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
x -=1

In [76]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x *=2

In [78]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [79]:
x + 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [80]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [84]:
y = np.sqrt(x)

In [85]:
y

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

In [86]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [88]:
np.log(x+1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])

In [89]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [90]:
a.sum()

105

In [91]:
a.min()

0

In [92]:
x += 1

In [94]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [95]:
x.min()

1

In [96]:
np.sin(x)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [97]:
np.sin(x)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849,
       -0.99999021,  0.42016704,  0.65028784, -0.96139749,  0.14987721])

In [98]:
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [99]:
x.max()

19

In [100]:
x.mean()

10.0

In [101]:
x.std()

5.744562646538029

In [103]:
a = np.arange(10,16)

In [104]:
a

array([10, 11, 12, 13, 14, 15])

In [105]:
a[0]

10

In [106]:
a[1]

11

In [107]:
a[4]

14

In [108]:
a[-1]

15

In [109]:
a[0]

10

In [110]:
a

array([10, 11, 12, 13, 14, 15])

In [111]:
a = np.arange(10)

In [112]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
a = np.sqrt(a)

In [114]:
a

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [115]:
a = np.arange(87)

In [116]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86])

In [117]:
a[-1]

86

In [118]:
a[-2]

85

In [119]:
a[[1,3,4]]

array([1, 3, 4])

In [120]:
a[[0,-1]]

array([ 0, 86])

In [121]:
a[[11,13,-2]]

array([11, 13, 85])

In [122]:
a[[11,13,-1]]

array([11, 13, 86])

In [124]:
a[[11,13,-2,86]]

array([11, 13, 85, 86])

In [127]:
a = np.arange(9).reshape(3,3)

In [128]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
a[1,2]

5

In [130]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [131]:
a[2,2]

8

In [132]:
a[0,0]

0

In [133]:
a[1,1]

4

In [134]:
a[11]

IndexError: index 11 is out of bounds for axis 0 with size 3

In [135]:
a[1]

array([3, 4, 5])

In [136]:
a[0]

array([0, 1, 2])

In [137]:
a = np.arange(16)

In [138]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [139]:
a[[6,7,8,9,10]]

array([ 6,  7,  8,  9, 10])

In [140]:
a  = np.arange(99)

In [141]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [142]:
a[22:88]

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87])

In [143]:
a += 1

In [144]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [145]:
a[22:88]

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88])

In [146]:
a[22:88:92]

array([23])

In [147]:
a[22:88:2]

array([23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55,
       57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87])

In [148]:
a[22:88:1]

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88])

In [149]:
a[22:88:-1]

array([], dtype=int64)

In [150]:
a[22:88:1]

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88])

In [151]:
a[22:88:2]

array([23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55,
       57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87])

In [152]:
a[22:88:3]

array([23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68, 71,
       74, 77, 80, 83, 86])

In [153]:
a[22:88:10]

array([23, 33, 43, 53, 63, 73, 83])

In [154]:
a = np.arange(100,200)

In [155]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [156]:
a[22:88:10]

array([122, 132, 142, 152, 162, 172, 182])

In [157]:
a[22:88:-1]

array([], dtype=int64)

In [158]:
a[88:22:-1]

array([188, 187, 186, 185, 184, 183, 182, 181, 180, 179, 178, 177, 176,
       175, 174, 173, 172, 171, 170, 169, 168, 167, 166, 165, 164, 163,
       162, 161, 160, 159, 158, 157, 156, 155, 154, 153, 152, 151, 150,
       149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138, 137,
       136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124,
       123])

In [159]:
a[::1]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [160]:
a[::2]

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198])

In [161]:
a[:5:]

array([100, 101, 102, 103, 104])

In [162]:
a = np.arange(10,19).reshape(3,3)

In [163]:
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [164]:
a[0]

array([10, 11, 12])

In [165]:
a[1]

array([13, 14, 15])

In [166]:
a[2]

array([16, 17, 18])

In [167]:
a[0,:]

array([10, 11, 12])

In [168]:
a[:,0]

array([10, 13, 16])

In [169]:
a[:,1]

array([11, 14, 17])

In [170]:
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [171]:
a[0:1,0:1]

array([[10]])

In [172]:
a[0:1,0:2]

array([[10, 11]])

In [173]:
a[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [174]:
a[[0,2],0:2]

array([[10, 11],
       [16, 17]])

In [175]:
a

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [180]:
for i in a :
    print(i)
    print("---")

[10 11 12]
---
[13 14 15]
---
[16 17 18]
---


In [178]:
a.flat

In [181]:
for item in a.flat:
    print(item)
    print("-----")

10
-----
11
-----
12
-----
13
-----
14
-----
15
-----
16
-----
17
-----
18
-----
