In [1]:
import pandas as pd
import numpy as np

In [3]:
s = pd.Series([12,-4,7,9])

In [4]:
s

0    12
1    -4
2     7
3     9
dtype: int64

In [5]:
s[0]

12

In [6]:
s[1]

-4

In [17]:
arr = np.arange(3)+4
s = pd.Series(arr)

In [18]:
s

0    4
1    5
2    6
dtype: int64

In [26]:
s = pd.Series([12,-7,4,9], index=['maths','maths','sst','hindi'])

In [27]:
s[0]

12

In [28]:
s['maths']

maths    12
maths    -7
dtype: int64

In [29]:
s.values

array([12, -7,  4,  9])

In [30]:
s.index

Index(['maths', 'maths', 'sst', 'hindi'], dtype='object')

In [31]:
s

maths    12
maths    -7
sst       4
hindi     9
dtype: int64

In [32]:
s + 7

maths    19
maths     0
sst      11
hindi    16
dtype: int64

In [33]:
s

maths    12
maths    -7
sst       4
hindi     9
dtype: int64

In [34]:
np.log(s+8)

maths    2.995732
maths    0.000000
sst      2.484907
hindi    2.833213
dtype: float64

In [35]:
s

maths    12
maths    -7
sst       4
hindi     9
dtype: int64

In [36]:
s = pd.Series([12,-7,4,9], index=['a','b','c','d'])

In [37]:
s[0]

12

In [38]:
s['a']

12

In [39]:
s[0:2]

a    12
b    -7
dtype: int64

In [40]:
s[['b','c']]

b   -7
c    4
dtype: int64

In [41]:
s[1] = 1

In [42]:
s

a    12
b     1
c     4
d     9
dtype: int64

In [43]:
s['b'] = -7

In [44]:
s

a    12
b    -7
c     4
d     9
dtype: int64

In [45]:
s = pd.Series([32,36,30,40], index=['a','b','c','d'])

In [46]:
s

a    32
b    36
c    30
d    40
dtype: int64

In [47]:
np.log(s)

a    3.465736
b    3.583519
c    3.401197
d    3.688879
dtype: float64

In [49]:
a = np.arange(16)

In [50]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
s = pd.Series(a)

In [53]:
s +7

0      7
1      8
2      9
3     10
4     11
5     12
6     13
7     14
8     15
9     16
10    17
11    18
12    19
13    20
14    21
15    22
dtype: int64

In [54]:
s = pd.Series([32,36,30,40], index=['a','b','c','d'])

In [55]:
s

a    32
b    36
c    30
d    40
dtype: int64

In [57]:
x = pd.Series(s)

In [58]:
x

a    32
b    36
c    30
d    40
dtype: int64

In [59]:
s

a    32
b    36
c    30
d    40
dtype: int64

In [60]:
s[0] = 23

In [61]:
s

a    23
b    36
c    30
d    40
dtype: int64

In [62]:
x

a    23
b    36
c    30
d    40
dtype: int64

In [63]:
x[0] = 0

In [64]:
s

a     0
b    36
c    30
d    40
dtype: int64

In [67]:
s = s / 7

In [68]:
s

a    0.000000
b    5.142857
c    4.285714
d    5.714286
dtype: float64

In [69]:
x

a     0
b    36
c    30
d    40
dtype: int64

In [70]:
s = pd.Series([12,-7,4,9])

In [71]:
s

0    12
1    -7
2     4
3     9
dtype: int64

In [73]:
x = s[s > 8]

In [74]:
x

0    12
3     9
dtype: int64

In [75]:
x[0] = 11

In [76]:
s

0    12
1    -7
2     4
3     9
dtype: int64

In [78]:
s[2]=7
x

0    11
3     9
dtype: int64

In [79]:
s

0    12
1    -7
2     7
3     9
dtype: int64

In [80]:
x

0    11
3     9
dtype: int64

In [81]:
s = pd.Series([12,-7,4,9], index=['a','b','c','d'])

In [82]:
x = s[s > 8]

In [83]:
x

a    12
d     9
dtype: int64

In [84]:
x[0]

12

In [85]:
x[1]

9

In [87]:
x['a']

12

In [88]:
x['d']

9

In [89]:
s / 2

a    6.0
b   -3.5
c    2.0
d    4.5
dtype: float64

In [90]:
s

a    12
b    -7
c     4
d     9
dtype: int64

In [91]:
s = pd.Series([12,-7,4,-7,4,9], index=['a','b','c','d','c','d'])

In [92]:
s

a    12
b    -7
c     4
d    -7
c     4
d     9
dtype: int64

In [93]:
s.unique()

array([12, -7,  4,  9])

In [94]:
s.value_counts()

-7     2
 4     2
 12    1
 9     1
dtype: int64

In [95]:
s = pd.Series([1,0,2,1,2,3],index=['white','white','blue','green','green','yellow'])

In [96]:
s

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

In [97]:
s.unique()

array([1, 0, 2, 3])

In [98]:
s.value_counts()

2    2
1    2
3    1
0    1
dtype: int64

In [100]:
s.isin([1,3])

white      True
white     False
blue      False
green      True
green     False
yellow     True
dtype: bool

In [101]:
s[s.isin([1,3])]

white     1
green     1
yellow    3
dtype: int64

In [102]:
s

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

In [103]:
s = pd.Series([12,-7,4,-7,4,9], index=['a','b','c','d','c','d'])

In [104]:
np.log(s)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


a    2.484907
b         NaN
c    1.386294
d         NaN
c    1.386294
d    2.197225
dtype: float64

In [107]:
x = pd.Series([12,np.NaN,4])

In [108]:
np.log(x)

0    2.484907
1         NaN
2    1.386294
dtype: float64

In [109]:
x

0    12.0
1     NaN
2     4.0
dtype: float64

In [110]:
x.isnull()

0    False
1     True
2    False
dtype: bool

In [111]:
x.notnull()

0     True
1    False
2     True
dtype: bool

In [112]:
x

0    12.0
1     NaN
2     4.0
dtype: float64

In [113]:
x[x.notnull()]

0    12.0
2     4.0
dtype: float64

In [114]:
np.mean(x[x.notnull()])

8.0

In [115]:
np.mean(x)

8.0

In [116]:
x[1] = -1


In [117]:
x

0    12.0
1    -1.0
2     4.0
dtype: float64

In [118]:
np.mean(x)

5.0

In [119]:
s

a    12
b    -7
c     4
d    -7
c     4
d     9
dtype: int64

In [120]:
mydict = {'red':2000, 'blue':1000,'yellow':500, 'orange':1000}

In [121]:
mydict

{'blue': 1000, 'orange': 1000, 'red': 2000, 'yellow': 500}

In [122]:
myseries = pd.Series(mydict)

In [123]:
myseries

blue      1000
orange    1000
red       2000
yellow     500
dtype: int64

In [124]:
myseries[0] = 99

In [125]:
myseries

blue        99
orange    1000
red       2000
yellow     500
dtype: int64

In [126]:
mydict

{'blue': 1000, 'orange': 1000, 'red': 2000, 'yellow': 500}

In [127]:
data = {'color' : ['blue','green','yellow','red','white'],
       'object' : ['ball','pen','pencil','paper','mug'],
       'price' : [1,2,3,4,5]}

In [128]:
data

{'color': ['blue', 'green', 'yellow', 'red', 'white'],
 'object': ['ball', 'pen', 'pencil', 'paper', 'mug'],
 'price': [1, 2, 3, 4, 5]}

In [129]:
frame = pd.DataFrame(data)

In [130]:
frame

color  object  price
0    blue    ball      1
1   green     pen      2
2  yellow  pencil      3
3     red   paper      4
4   white     mug      5

In [132]:
frame = pd.DataFrame(data,columns=['object','price'])

In [133]:
frame

object  price
0    ball      1
1     pen      2
2  pencil      3
3   paper      4
4     mug      5

In [134]:
frame = pd.DataFrame(data,columns=['price','object'])

In [135]:
frame

price  object
0      1    ball
1      2     pen
2      3  pencil
3      4   paper
4      5     mug

In [136]:
frame = pd.DataFrame(data)
frame

color  object  price
0    blue    ball      1
1   green     pen      2
2  yellow  pencil      3
3     red   paper      4
4   white     mug      5

In [137]:
frame = pd.DataFrame(data,index=['one','two','write','four','five'])

In [138]:
frame

color  object  price
one      blue    ball      1
two     green     pen      2
write  yellow  pencil      3
four      red   paper      4
five    white     mug      5

In [139]:
frame = pd.DataFrame(np.arange(25).reshape(5,5),
                     index=['one','two','write','four','five'], columns=['ball','pen','pencil','paper','mug'])

In [140]:
frame

ball  pen  pencil  paper  mug
one       0    1       2      3    4
two       5    6       7      8    9
write    10   11      12     13   14
four     15   16      17     18   19
five     20   21      22     23   24

In [141]:
frame.columns

Index(['ball', 'pen', 'pencil', 'paper', 'mug'], dtype='object')

In [142]:
frame.index

Index(['one', 'two', 'write', 'four', 'five'], dtype='object')

In [143]:
frame.values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])